import {
  GlobalSettings,
  HeaderConfig,
  TopBarConfig,
  NavigationMenuItem,
  FooterConfig,
  HeroConfig,
  ProgramScheduleSectionConfig,
  OfflineRegistrationCenter,
  SchoolInfo,
  AssociationInfo,
  Notice,
  FAQItem,
  CommitteeMember
} from '../types';

export const INITIAL_GLOBAL_SETTINGS: GlobalSettings = {
  site_name_en: 'Nanupur Abu Sobhan High School Alumni Association',
  site_name_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ',
  site_tagline_en: '85 Years of Heritage, Friendship & Memories',
  site_tagline_bn: '৮৫ বছরের ঐতিহ্য, বন্ধুত্ব ও স্মৃতির মেলবন্ধন',
  site_description_en: 'Official bilingual platform for Nanupur Abu Sobhan High School Alumni Association and the 85th Anniversary Celebration & Alumni Reunion (16 January 2027).',
  site_description_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ ও ৮৫ বছর পূর্তি পুনর্মিলনী ২০২৭ এর অফিসিয়াল ডিজিটাল প্ল্যাটফর্ম।',
  logo_url: '',
  mobile_logo_url: '',
  favicon_url: '/favicon.ico',
  primary_color: '#0f4d2a',
  secondary_color: '#135d34',
  accent_color: '#d4971c',
  background_color: '#f8fafc',
  font_family: 'Hind Siliguri, Plus Jakarta Sans, sans-serif',
  default_language: 'bn',
  available_languages: ['bn', 'en'],
  copyright_en: '© 2027 Nanupur Abu Sobhan High School Alumni Association. All rights reserved.',
  copyright_bn: '© ২০২৭ নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ। সর্বস্বত্ব সংরক্ষিত।',
  contact_email: 'info@nanupuralumni.org',
  contact_phone: '+880 1819-123456',
  google_maps_url: 'https://maps.google.com/?q=Nanupur+Abu+Sobhan+High+School',
  office_hours_en: 'Saturday to Thursday: 09:00 AM - 05:00 PM',
  office_hours_bn: 'শনিবার থেকে বৃহস্পতিবার: সকাল ৯:০০ টা - বিকাল ৫:০০ টা',
  address_en: 'Nanupur Abu Sobhan High School Premises, Nanupur, Fatikchhari, Chattogram 4350, Bangladesh.',
  address_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাঙ্গণ, নানুপুর, ফটিকছড়ি, চট্টগ্রাম ৪৩৫০, বাংলাদেশ।',
  seo_default_title: 'NASH Alumni Association & 85th Anniversary Reunion 2027',
  seo_meta_description: 'Register online for the 85th Anniversary Celebration of Nanupur Abu Sobhan High School (16 Jan 2027). Instant bKash/Nagad payment & secure QR entry pass.',
  seo_og_image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
  search_engine_indexing: true,
  robots_txt: 'User-agent: *\nAllow: /',
  social_links: {
    facebook: 'https://facebook.com/nashalumni',
    youtube: 'https://youtube.com/@nashalumni',
    twitter: 'https://twitter.com/nashalumni',
    linkedin: 'https://linkedin.com/company/nash-alumni',
    instagram: 'https://instagram.com/nashalumni',
  },
};

export const INITIAL_TOPBAR_CONFIG: TopBarConfig = {
  is_enabled: true,
  announcement_en: '16 January 2027 • Saturday',
  announcement_bn: '১৬ জানুয়ারি ২০২৭ • শনিবার',
  show_notice_indicator: true,
  show_contact_info: true,
  contact_phone: '+880 1819-123456',
  contact_email: 'info@nanupuralumni.org',
  show_login_link: true,
  show_registration_link: true,
  show_language_selector: true,
  show_social_icons: true,
  custom_cta_text_en: 'Register Now',
  custom_cta_text_bn: 'নিবন্ধন করুন',
  custom_cta_url: '#register',
};

export const INITIAL_HEADER_CONFIG: HeaderConfig = {
  logo_url: '',
  mobile_logo_url: '',
  logo_link: '/',
  show_search: true,
  show_cta_button: true,
  cta_text_en: 'Register for 85th Reunion',
  cta_text_bn: 'অনলাইনে নিবন্ধন করুন',
  cta_url: 'register',
  show_language_switcher: true,
  show_user_menu: true,
};

export const INITIAL_MENUS: NavigationMenuItem[] = [
  {
    id: 'menu-home',
    url: '/',
    order: 1,
    target: '_self',
    label_bn: 'মূলপাতা',
    label_en: 'Home',
    is_active: true,
  },
  {
    id: 'menu-about',
    url: '#about',
    order: 2,
    target: '_self',
    label_bn: 'পরিচিতি',
    label_en: 'About',
    is_active: true,
    children: [
      {
        id: 'menu-about-school',
        url: '#school',
        order: 1,
        target: '_self',
        label_bn: 'বিদ্যালয়ের ঐতিহ্য',
        label_en: 'School Heritage',
        is_active: true,
        parent_id: 'menu-about',
      },
      {
        id: 'menu-about-association',
        url: '#association',
        order: 2,
        target: '_self',
        label_bn: 'প্রাক্তন শিক্ষার্থী পরিষদ',
        label_en: 'Alumni Association',
        is_active: true,
        parent_id: 'menu-about',
      },
      {
        id: 'menu-about-committee',
        url: '#committee',
        order: 3,
        target: '_self',
        label_bn: 'কার্যনির্বাহী পরিষদ',
        label_en: 'Executive Committee',
        is_active: true,
        parent_id: 'menu-about',
      },
      {
        id: 'menu-about-history',
        url: '#history',
        order: 4,
        target: '_self',
        label_bn: 'পুনর্মিলনীর ইতিহাস',
        label_en: 'Reunion History',
        is_active: true,
        parent_id: 'menu-about',
      },
    ],
  },
  {
    id: 'menu-notices',
    url: '#notices',
    order: 3,
    target: '_self',
    label_bn: 'বিজ্ঞপ্তি',
    label_en: 'Notices & Circulars',
    is_active: true,
  },
  {
    id: 'menu-news',
    url: '#news',
    order: 4,
    target: '_self',
    label_bn: 'খবর ও আপডেট',
    label_en: 'News & Updates',
    is_active: true,
  },
  {
    id: 'menu-verify',
    url: '#verify',
    order: 6,
    target: '_self',
    label_bn: 'পাস যাচাই',
    label_en: 'Verify Pass',
    is_active: true,
  },
  {
    id: 'menu-contact',
    url: '#contact',
    order: 7,
    target: '_self',
    label_bn: 'যোগাযোগ',
    label_en: 'Contact',
    is_active: true,
  },
];

export const INITIAL_FOOTER_CONFIG: FooterConfig = {
  logo_url: '',
  description_en: 'Nanupur Abu Sobhan High School Alumni Association connects thousands of proud alumni worldwide, uniting generations in celebration of our heritage.',
  description_bn: '১৯৪২ সাল থেকে জ্ঞান, নৈতিকতা ও মানবিক মূল্যবোধের আলো ছড়িয়ে ৮৫ বছর পূর্ণ করতে চলেছে আমাদের প্রিয় বিদ্যাপীঠ।',
  address_en: 'Nanupur, Fatikchhari, Chattogram 4350, Bangladesh',
  address_bn: 'বিদ্যালয় প্রাঙ্গণ, নানুপুর, ফটিকছড়ি, চট্টগ্রাম',
  phone: '+880 1819-123456',
  email: 'info@nanupuralumni.org',
  copyright_en: '© 1942–2027 Nanupur Abu Sobhan High School Alumni Association. All rights reserved.',
  copyright_bn: '© ১৯৪২–২০২৭ নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ। সর্বস্বত্ব সংরক্ষিত।',
  social_links: {
    facebook: 'https://facebook.com/nashalumni',
    youtube: 'https://youtube.com/@nashalumni',
  },
  columns: [
    {
      id: 'col-event',
      title_en: '85th Anniversary Event',
      title_bn: '৮৫ বছর পূর্তি উৎসব',
      order: 1,
      is_active: true,
      links: [
        { id: 'lnk-1', label_en: 'Register for Reunion', label_bn: 'অনলাইনে নিবন্ধন করুন', url: '#register', target: '_self', order: 1, is_active: true },
        { id: 'lnk-2', label_en: 'Verify Token Code', label_bn: 'ডিজিটাল পাস যাচাই', url: '#verify', target: '_self', order: 2, is_active: true },
        { id: 'lnk-3', label_en: 'Reunion History', label_bn: 'পুনর্মিলনীর ইতিহাস', url: '#history', target: '_self', order: 3, is_active: true },
        { id: 'lnk-4', label_en: 'Latest Official Notices', label_bn: 'দাপ্তরিক নোটিশসমূহ', url: '#notices', target: '_self', order: 4, is_active: true },
      ],
    },
    {
      id: 'col-org',
      title_en: 'Organization & Heritage',
      title_bn: 'পরিচিতি ও পরিষদ',
      order: 2,
      is_active: true,
      links: [
        { id: 'lnk-5', label_en: 'School Heritage & History', label_bn: 'বিদ্যালয়ের গৌরবময় ইতিহাস', url: '#school', target: '_self', order: 1, is_active: true },
        { id: 'lnk-6', label_en: 'Alumni Association Mission', label_bn: 'প্রাক্তন শিক্ষার্থী পরিষদ', url: '#association', target: '_self', order: 2, is_active: true },
        { id: 'lnk-7', label_en: 'Executive Committee', label_bn: 'কার্যনির্বাহী পরিষদ', url: '#committee', target: '_self', order: 3, is_active: true },
        { id: 'lnk-8', label_en: 'Contact Secretariat', label_bn: 'সরাসরি যোগাযোগ ও সহায়তা', url: '#contact', target: '_self', order: 4, is_active: true },
      ],
    },
  ],
};

export const INITIAL_HERO_CONFIG: HeroConfig = {
  badge_en: '1942–2027 • 85 Glorious Years of Legacy',
  badge_bn: '১৯৪২–২০২৭ • ৮৫ বছরের গৌরবময় ঐতিহ্য',
  show_badge: true,
  headline_en: '85th Anniversary Celebration &',
  headline_bn: '৮৫ বছর পূর্তি উৎসব ও',
  headline_highlight_en: 'Grand Alumni Reunion 2027',
  headline_highlight_bn: 'প্রাক্তন শিক্ষার্থী পুনর্মিলনী ২০২৭',
  subheading_en: 'Welcoming all beloved alumni of Nanupur Abu Sobhan High School to an unforgettable reunion of camaraderie, nostalgia, and community.',
  subheading_bn: 'ঐতিহ্যবাহী নানুপুর আবু সোবহান উচ্চ বিদ্যালয়ের সকল প্রাক্তন শিক্ষার্থীকে প্রাণঢালা আমন্ত্রণ। আসুন শৈশব ও কৈশোরের সোনালী স্মৃতিতে অবগাহন করি।',
  date_text_en: '16 January 2027 (Saturday)',
  date_text_bn: '১৬ জানুয়ারি ২০২৭ (শনিবার)',
  show_date: true,
  venue_text_en: 'Nanupur Abu Sobhan High School Campus',
  venue_text_bn: 'বিদ্যালয় প্রাঙ্গণ, নানুপুর, ফটিকছড়ি, চট্টগ্রাম',
  show_venue: true,
  fee_text_en: 'Registration Fee: ৳1,000 BDT',
  fee_text_bn: 'নিবন্ধন ফি: ১,০০০ টাকা',
  show_fee: true,
  primary_cta_text_en: 'Register for Reunion Now',
  primary_cta_text_bn: 'অনলাইনে নিবন্ধন করুন',
  primary_cta_link: 'register',
  show_primary_cta: true,
  secondary_cta_text_en: 'Verify Token Code',
  secondary_cta_text_bn: 'পাস যাচাই করুন',
  secondary_cta_link: 'verify',
  show_secondary_cta: true,
  countdown_target_date: '2027-01-16T08:00:00+06:00',
  countdown_label_en: 'Countdown to Historic Reunion',
  countdown_label_bn: 'উৎসব শুরু হতে বাকি',
  show_countdown: true,
  background_style: 'gradient',
  background_image_url: '',
  hero_image_url: '',
  overlay_opacity: 20,
  accent_color: '#fbbf24',
};

export const INITIAL_PROGRAM_SCHEDULE: ProgramScheduleSectionConfig = {
  is_enabled: true,
  badge_en: 'Event Schedule & Festivities',
  badge_bn: 'উদযাপন কর্মসূচি ও উৎসব সূচি',
  title_en: 'A Day of Nostalgia, Honor & Celebration',
  title_bn: 'স্মৃতিচারণ, সম্মাননা ও মহা মিলনমেলার পূর্ণাঙ্গ সূচি',
  subtitle_en: 'Saturday, 16 January 2027 • A meticulously planned full-day celebration on the school campus.',
  subtitle_bn: '১৬ জানুয়ারি ২০২৭, শনিবার • বিদ্যালয় প্রাঙ্গণে সারাদিনব্যাপী বর্ণাঢ্য আয়োজন।',
  items: [
    {
      id: 'sched-1',
      time: '08:30 AM – 10:00 AM',
      order: 1,
      title_en: 'Reception & Commemorative Kit Distribution',
      title_bn: 'অভ্যর্থনা, উপহার কিট ও স্মরণিকা বিতরণ',
      description_en: 'Present your QR token pass to collect the commemorative bag, custom polo, 85th Souvenir book, and badge.',
      description_bn: 'ডিজিটাল প্রবেশপত্র স্ক্যান করে গ্রহণ করুন বিশেষ স্মারক ব্যাগ, টি-শার্ট, ক্যাপ ও ৮৫তম বর্ষের স্মরণিকা গ্রন্থ।',
      icon: 'gift',
      is_active: true,
    },
    {
      id: 'sched-2',
      time: '10:00 AM – 11:30 AM',
      order: 2,
      title_en: 'Heritage Rally & Flag Ceremony',
      title_bn: 'আনন্দ শোভাযাত্রা ও উদ্বোধন',
      description_en: 'National anthem, unfurling of national & school flags, release of doves, and a colorful alumni procession across Nanupur.',
      description_bn: 'জাতীয় সংগীত, জাতীয় ও বিদ্যালয়ের পতাকা উত্তোলন, শান্তির প্রতীক পায়রা উড্ডয়ন এবং নানুপুর বাজারে বর্ণাঢ্য শোভাযাত্রা।',
      icon: 'users',
      is_active: true,
    },
    {
      id: 'sched-3',
      time: '11:30 AM – 01:30 PM',
      order: 3,
      title_en: 'Teacher Honor & Memorial Remembrances',
      title_bn: 'শিক্ষক সম্মাননা ও গুণীজন সংবর্ধনা',
      description_en: 'Felicitation of retired & serving teachers, presentation of lifetime achievement awards, and tribute to departed souls.',
      description_bn: 'শ্রদ্ধেয় অবসরপ্রাপ্ত ও কর্মরত শিক্ষকবৃন্দের সম্মাননা প্রদান এবং পরলোকগত শিক্ষক-শিক্ষার্থীদের স্মরণে বিশেষ শ্রদ্ধাঞ্জলি।',
      icon: 'award',
      is_active: true,
    },
    {
      id: 'sched-4',
      time: '01:30 PM – 03:00 PM',
      order: 4,
      title_en: 'Grand Traditional Mezban Feast & Prayer',
      title_bn: 'ঐতিহ্যবাহী মেজবান ভোজ ও নামাজ',
      description_en: 'Sumptuous authentic Chattogram banquet for thousands of alumni, teachers, and guests with traditional hospitality.',
      description_bn: 'হাজারো প্রাক্তন শিক্ষার্থী, শিক্ষক ও অতিথিদের জন্য চট্টগ্রামের ঐতিহ্যবাহী রাজকীয় মেজবান ভোজ ও নামাজ।',
      icon: 'utensils',
      is_active: true,
    },
    {
      id: 'sched-5',
      time: '03:00 PM – 05:30 PM',
      order: 5,
      title_en: 'Batch Reunions & Open Microphone Nostalgia',
      title_bn: 'ব্যাচভিত্তিক স্মৃতিচারণ ও আড্ডা',
      description_en: 'Dedicated designated zones for every batch decade (1940s to 2020s), open-mic childhood stories, and group photo sessions.',
      description_bn: 'ব্যাচভিত্তিক নির্দিষ্ট প্যাভিলিয়নে পুরনো বন্ধুদের আড্ডা, স্মৃতিচারণ এবং সহপাঠীদের সাথে বিশেষ ফটোসেশন।',
      icon: 'heart-handshake',
      is_active: true,
    },
    {
      id: 'sched-6',
      time: '05:30 PM – 09:00 PM',
      order: 6,
      title_en: 'Grand Cultural Evening & Laser Spectacle',
      title_bn: 'জমকালো সাংস্কৃতিক সন্ধ্যা ও আলোক উৎসব',
      description_en: 'Performances by celebrated national artists, traditional folk music, student dramas, and a grand anniversary fireworks finale.',
      description_bn: 'জনপ্রিয় জাতীয় শিল্পীদের সঙ্গীত পরিবেশনা, নাটিকা, স্মৃতিময় তথ্যচিত্র প্রদর্শন ও বর্ণিল আতশবাজির উৎসব।',
      icon: 'sparkles',
      is_active: true,
    },
  ],
};

export const INITIAL_OFFLINE_CENTERS: OfflineRegistrationCenter[] = [
  {
    id: 'booth-1',
    name_en: 'Campus Secretariat Helpdesk',
    name_bn: 'বিদ্যালয় প্রধান ক্যাম্পাসের বুথ',
    address_en: 'Headmaster Secretariat, Nanupur Abu Sobhan High School Premises, Fatikchhari, Chattogram',
    address_bn: 'প্রধান শিক্ষকের কার্যালয় সংলগ্ন, বিদ্যালয় ক্যাম্পাস, নানুপুর, ফটিকছড়ি, চট্টগ্রাম',
    phone: '01819-000001',
    contact_person: 'Master Nurul Absar (Senior Teacher)',
    contact_person_bn: 'মাস্টার নুরুল আবছার (সিনিয়র শিক্ষক)',
    timings: 'Daily 09:00 AM – 04:30 PM',
    timings_bn: 'প্রতিদিন সকাল ০৯:০০ টা – বিকাল ০৪:৩০ টা',
    description_en: 'Primary on-campus verification, token issuance, and cash collection booth.',
    description_bn: 'বিদ্যালয় প্রাঙ্গণে সরাসরি নিবন্ধন ফর্ম পূরণ ও তাৎক্ষণিক প্রবেশপত্র প্রাপ্তির প্রধান বুথ।',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'booth-2',
    name_en: 'Nanupur Central Bazar Center',
    name_bn: 'নানুপুর বাজার নিবন্ধন বুথ',
    address_en: 'Sobhan Market (Ground Floor), Nanupur Bazar, Fatikchhari, Chattogram',
    address_bn: 'সোবহান মার্কেট (নিচতলা), নানুপুর বাজার, ফটিকছড়ি, চট্টগ্রাম',
    phone: '01819-000002',
    contact_person: 'Alhaj Faruk Ahmed (Bazar Coordinator)',
    contact_person_bn: 'আলহাজ্ব ফারুক আহমেদ (বাজার সমন্বয়ক)',
    timings: 'Daily 10:00 AM – 08:00 PM',
    timings_bn: 'প্রতিদিন সকাল ১০:০০ টা – রাত ০৮:০০ টা',
    description_en: 'Convenient commercial hub center for local alumni and business owners.',
    description_bn: 'স্থানীয় ব্যবসায়ী ও প্রাক্তন শিক্ষার্থীদের জন্য বাজার সংলগ্ন সুপরিসর তথ্য ও নিবন্ধন কেন্দ্র।',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'booth-3',
    name_en: 'Chattogram Metropolitan Liaison Desk',
    name_bn: 'চট্টগ্রাম মহানগর তথ্য ও নিবন্ধন ডেস্ক',
    address_en: 'Nash Liaison Office, GEC Circle / Nasirabad, Chattogram',
    address_bn: 'জিইসি মোড় / নাসিরাবাদ, চট্টগ্রাম মহানগর',
    phone: '01819-000003',
    contact_person: 'Engr. Dhrubo Chowdhury (Urban Chapter)',
    contact_person_bn: 'প্রকৌ. ধ্রুব চৌধুরী (মহানগর সমন্বয়ক)',
    timings: 'Sat – Thu: 11:00 AM – 07:00 PM',
    timings_bn: 'শনিবার – বৃহস্পতিবার: সকাল ১১:০০ টা – সন্ধ্যা ০৭:০০ টা',
    description_en: 'Facilitating city-resident alumni registration, batch groups, and token handovers.',
    description_bn: 'চট্টগ্রাম শহরে বসবাসরত প্রাক্তন শিক্ষার্থীদের জন্য সেন্ট্রাল বুথ ও হেল্পডেস্ক।',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'booth-4',
    name_en: 'Dhaka Chapter Coordination Desk',
    name_bn: 'ঢাকা সমন্বয় ডেস্ক',
    address_en: 'NASH Alumni Liaison Center, Dhanmondi / Motijheel, Dhaka',
    address_bn: 'ধানমন্ডি / মতিঝিল, ঢাকা',
    phone: '01819-000004',
    contact_person: 'Dr. Rafiqul Huq (Dhaka Alumni Coordinator)',
    contact_person_bn: 'ড. রফিকুল হক (ঢাকা চ্যাপ্টার সমন্বয়ক)',
    timings: 'Sun – Thu: 03:00 PM – 08:00 PM',
    timings_bn: 'রবি – বৃহস্পতি: বিকাল ০৩:০০ টা – রাত ০৮:০০ টা',
    description_en: 'Assisting capital city alumni, senior batches, and diaspora coordination.',
    description_bn: 'রাজধানী ঢাকায় কর্মরত ও বসবাসরত প্রাক্তন শিক্ষার্থীদের নিবন্ধন সমন্বয় কেন্দ্র।',
    order_index: 4,
    is_active: true,
  },
];

export const INITIAL_SCHOOL_INFO: SchoolInfo = {
  name_en: 'Nanupur Abu Sobhan High School',
  name_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয়',
  established_year: 1942,
  eiin_number: '104321',
  history_en: 'Founded in 1942 by the visionary philanthropist Late Alhaj Abu Sobhan, our beloved institution has stood as an illustrious citadel of learning, character building, and academic excellence in northern Chattogram for eighty-five glorious years.',
  history_bn: '১৯৪২ সালে প্রখ্যাত শিক্ষানুরাগী ও সমাজসেবক মরহুম আলহাজ্ব আবু সোবহানের মহতী উদ্যোগে এই বিদ্যাপীঠ প্রতিষ্ঠিত হয়। উত্তর চট্টগ্রামের শিক্ষা ও সংস্কৃতির অগ্রগতিতে বিদ্যালয়টি বিগত ৮৫ বছর ধরে আলোকবর্তিকা হিসেবে কাজ করে আসছে।',
  headmaster_name_en: 'Alhaj Mohammad Shahidul Alam',
  headmaster_name_bn: 'আলহাজ্ব মোহাম্মদ শহীদুল আলম',
  headmaster_message_en: 'It is a profound honor to welcome generations of our esteemed alumni back to their beloved school for the historic 85th Anniversary Celebration. May this grand reunion inspire our current students and strengthen our shared commitment to educational advancement.',
  headmaster_message_bn: 'বিদ্যালয়ের গৌরবোজ্জ্বল ৮৫ বছর পূর্তি উৎসবে সকল প্রাক্তন শিক্ষার্থীকে আন্তরিক শুভেচ্ছা ও অভিনন্দন। আপনাদের অকৃত্রিম ভালোবাসা ও সহযোগিতা বিদ্যালয়কে উত্তরোত্তর সাফল্যের শীর্ষে পৌঁছে দেবে—এই আমার দৃঢ় বিশ্বাস।',
  former_headmasters: [
    { name_en: 'Late Moulvi Mohammad Ishaq', name_bn: 'মরহুম মৌলভী মোহাম্মদ ইছহাক', period: '1942 – 1958' },
    { name_en: 'Late Abdul Mannan Chowdhury', name_bn: 'মরহুম আবদুল মান্নান চৌধুরী', period: '1958 – 1974' },
    { name_en: 'Late Md. Nurul Huda', name_bn: 'মরহুম মো. নুরুল হুদা', period: '1974 – 1991' },
    { name_en: 'Md. Shamsul Alam', name_bn: 'মো. শামসুল আলম', period: '1991 – 2008' },
    { name_en: 'Alhaj Md. Shahidul Alam', name_bn: 'আলহাজ্ব মো. শহীদুল আলম', period: '2008 – Present' },
  ],
  address_en: 'Nanupur Abu Sobhan High School Premises, Nanupur, Fatikchhari, Chattogram 4350, Bangladesh.',
  address_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাঙ্গণ, নানুপুর, ফটিকছড়ি, চট্টগ্রাম ৪৩৫০, বাংলাদেশ।',
  phone: '+880 1819-123456',
  email: 'info@nanupuralumni.org',
  facilities: [
    'আধুনিক বিজ্ঞানাগার (Modern Physics, Chemistry & Biology Labs)',
    'শেখ রাসেল ডিজিটাল ল্যাব (Sheikh Russel Digital ICT Lab)',
    'সমৃদ্ধ গ্রন্থাগার (Central Library with 10,000+ Books)',
    'বিশাল খেলার মাঠ (Multi-purpose Sports Grounds)',
    'মাল্টিমিডিয়া ক্লাসরুম (Interactive Multimedia Classrooms)',
    'সমন্বিত সিসিটিভি নিরাপত্তা ব্যবস্থা (24/7 CCTV Campus Surveillance)',
  ],
};

export const INITIAL_ASSOCIATION_INFO: AssociationInfo = {
  name_en: 'Nanupur Abu Sobhan High School Alumni Association',
  name_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ',
  established_year: 1985,
  intro_en: 'Uniting alumni across all generations in service, fellowship, and advancement of our beloved institution.',
  intro_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয়ের দেশ-বিদেশে অবস্থানরত সকল প্রাক্তন শিক্ষার্থীদের মেলবন্ধন ও সার্বিক উন্নয়নে নিবেদিত।',
  mission_en: 'Supporting student scholarships, advancing school infrastructure, preserving institutional heritage, and strengthening lifelong alumni fellowship across generations.',
  mission_bn: 'বিদ্যালয়ের দরিদ্র ও মেধাবী শিক্ষার্থীদের বৃত্তি প্রদান, বিজ্ঞানাগার ও পাঠাগার সমৃদ্ধকরণ এবং সকল ব্যাচের মধ্যে সুদৃঢ় ভ্রাতৃত্ববোধ গড়ে তোলা।',
  vision_en: 'A thriving global alumni community empowering future generations and championing institutional excellence for the next century.',
  vision_bn: 'একটি গতিশীল ও আন্তর্জাতিক প্রাক্তন শিক্ষার্থী নেটওয়ার্ক যা বিদ্যালয় ও সমাজ গঠনে পথিকৃৎ হিসেবে কাজ করবে।',
  objectives_en: [
    'Establish permanent need-based and merit scholarships for deserving students.',
    'Build a modern multi-storey STEM laboratory and auditorium complex.',
    'Create an updated digital archive of all 85 passing batches since 1942.',
    'Organize career mentorship sessions between senior alumni and students.',
  ],
  objectives_bn: [
    'মেধাবী ও অসচ্ছল শিক্ষার্থীদের জন্য স্থায়ী শিক্ষা বৃত্তি তহবিল পরিচালনা।',
    'বিদ্যালয়ে অত্যাধুনিক বিজ্ঞান ও তথ্যপ্রযুক্তি গবেষণাগার স্থাপন।',
    '১৯৪২ সাল থেকে সকল ব্যাচের শিক্ষার্থীদের সুসংগঠিত ডিজিটাল ডাটাবেজ সংরক্ষণ।',
    'বর্তমান শিক্ষার্থীদের পেশাগত পরামর্শ ও ক্যারিয়ার গাইডলাইন সহায়তা প্রদান।',
  ],
  contact_phone: '+880 1819-123456',
  contact_email: 'info@nanupuralumni.org',
  address_en: 'Nanupur Abu Sobhan High School Premises, Nanupur, Fatikchhari, Chattogram 4350, Bangladesh.',
  address_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাঙ্গণ, নানুপুর, ফটিকছড়ি, চট্টগ্রাম ৪৩৫০, বাংলাদেশ।',
};

export const INITIAL_COMMITTEE: CommitteeMember[] = [
  {
    id: 'comm-1',
    name_en: 'Engr. Afsar Uddin Ahmed',
    name_bn: 'প্রকৌ. আফসার উদ্দিন আহমেদ',
    designation_en: 'President / Convener',
    designation_bn: 'সভাপতি / আহ্বায়ক',
    batch_year: 1978,
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    tenure: '2025 – 2027',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'comm-2',
    name_en: 'Advocate Mahfuzur Rahman',
    name_bn: 'অ্যাডভোকেট মাহফুজুর রহমান',
    designation_en: 'Senior Vice President',
    designation_bn: 'সিনিয়র সহ-সভাপতি',
    batch_year: 1982,
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    tenure: '2025 – 2027',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'comm-3',
    name_en: 'Dr. Shahadat Hossain',
    name_bn: 'ডা. শাহাদাত হোসেন',
    designation_en: 'General Secretary / Member Secretary',
    designation_bn: 'সাধারণ সম্পাদক / সদস্য সচিব',
    batch_year: 1988,
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    tenure: '2025 – 2027',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'comm-4',
    name_en: 'Alhaj Khorshed Alam',
    name_bn: 'আলহাজ্ব খোরশেদ আলম',
    designation_en: 'Finance Secretary / Treasurer',
    designation_bn: 'অর্থ সম্পাদক / কোষাধ্যক্ষ',
    batch_year: 1991,
    photo_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    tenure: '2025 – 2027',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'comm-5',
    name_en: 'Master Nurul Absar',
    name_bn: 'মাস্টার নুরুল আবছার',
    designation_en: 'Organizing Secretary',
    designation_bn: 'সাংগঠনিক সম্পাদক',
    batch_year: 1995,
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    tenure: '2025 – 2027',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'comm-6',
    name_en: 'Barrister Tanveer Hasan',
    name_bn: 'ব্যারিস্টার তানভীর হাসান',
    designation_en: 'Legal & Constitutional Affairs Secretary',
    designation_bn: 'আইন ও সংবিধান বিষয়ক সম্পাদক',
    batch_year: 2002,
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    tenure: '2025 – 2027',
    order_index: 6,
    is_active: true,
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'notice-85-01',
    title_en: 'Online Registration Commences for 85th Anniversary & Grand Reunion 2027',
    title_bn: '৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনী ২০২৭ এর অনলাইন নিবন্ধন শুরু হয়েছে',
    publish_date: '2026-02-01',
    is_featured: true,
    is_active: true,
    category: 'Registration',
    content_en: 'The Executive Committee gladly announces that online registration for the historic 85th Anniversary celebration (16 January 2027) is officially underway. All beloved alumni from 1942 to the present are warmly encouraged to complete their registration and obtain their encrypted Digital Token Pass.',
    content_bn: 'ঐতিহ্যবাহী নানুপুর আবু সোবহান উচ্চ বিদ্যালয়ের ৮৫ বছর পূর্তি উৎসব ও মহা পুনর্মিলনী ২০২৭ এর অনলাইন নিবন্ধন আনুষ্ঠানিকভাবে উন্মুক্ত করা হয়েছে। দেশ ও প্রবাসে অবস্থানরত সকল ব্যাচের প্রাক্তন শিক্ষার্থীদের যথাশীঘ্র নিবন্ধন সম্পন্ন করে ডিজিটাল প্রবেশ টোকেন সংগ্রহ করার জন্য অনুরোধ করা যাচ্ছে।',
  },
  {
    id: 'notice-85-02',
    title_en: 'Authorized Offline Registration Centers Now Operational Across Chattogram & Dhaka',
    title_bn: 'চট্টগ্রাম ও ঢাকায় অফলাইন নিবন্ধন বুথ উদ্বোধন',
    publish_date: '2026-02-15',
    is_featured: true,
    is_active: true,
    category: 'Offices',
    content_en: 'In addition to our instant online payment gateway, authorized offline registration booths are actively accepting manual registrations and providing on-the-spot token passes at the school campus, Nanupur Bazar, Chattogram Liaison Desk, and Dhaka Coordination Desk.',
    content_bn: 'অনলাইন পেমেন্টের পাশাপাশি বিদ্যালয় প্রধান ক্যাম্পাস, নানুপুর বাজার, চট্টগ্রাম মহানগর এবং ঢাকায় অবস্থিত নির্ধারিত অফলাইন বুথ থেকে সরাসরি নিবন্ধন সম্পন্ন ও প্রবেশপত্র সংগ্রহ করা যাবে।',
  },
  {
    id: 'notice-85-03',
    title_en: 'Invitation for Commemorative Souvenir Articles, Childhood Photographs & Reminiscences',
    title_bn: '৮৫তম বর্ষপূর্তি স্মরণিকা গ্রন্থের জন্য লেখা ও ছবি আহ্বান',
    publish_date: '2026-03-01',
    is_featured: false,
    is_active: true,
    category: 'Publication',
    content_en: 'The Souvenir Sub-committee invites articles, poetry, memoirs, historical anecdotes, and vintage photographs regarding student life at Nanupur Abu Sobhan High School for inclusion in the grand 85th Souvenir publication.',
    content_bn: '৮৫ বছর পূর্তি উপলক্ষে প্রকাশিতব্য ঐতিহ্যবাহী স্মরণিকা গ্রন্থের জন্য প্রাক্তন শিক্ষক ও শিক্ষার্থীদের নিকট থেকে স্মৃতিচারণমূলক লেখা, কবিতা ও ঐতিহাসিক আলোকচিত্র আহ্বান করা যাচ্ছে।',
  },
];

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Registration & Fees',
    question_en: 'How much is the registration fee for the 85th Anniversary Celebration?',
    question_bn: '৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনীর নিবন্ধন ফি কত?',
    answer_en: 'The registration fee is BDT 1,000 per alumnus. It covers the commemorative anniversary bag, celebration badge, souvenir book, morning snacks, grand banquet lunch, evening tea, and cultural evening admission.',
    answer_bn: 'প্রতিজন প্রাক্তন শিক্ষার্থীর নিবন্ধন ফি ১,০০০ টাকা। এর মধ্যে রয়েছে স্মরণিকা ব্যাগ, মেডেল/ব্যাজ, স্মরণিকা বই, প্রাতঃরাশ, ঐতিহ্যবাহী মেজবান মধ্যাহ্নভোজ, সান্ধ্যকালীন নাশতা এবং জমকালো সাংস্কৃতিক অনুষ্ঠান।',
    order: 1,
    is_active: true,
  },
  {
    id: 'faq-2',
    category: 'Batch Information',
    question_en: 'How is my batch number determined?',
    question_bn: 'আমার ব্যাচ নম্বর কীভাবে নির্ধারিত হবে?',
    answer_en: 'Your batch is automatically computed based on your SSC passing year according to our institutional archive where Batch 2008 represents the 65th SSC batch.',
    answer_bn: 'আপনার এসএসসি পাসের সাল অনুযায়ী বিদ্যালয়ের প্রাতিষ্ঠানিক হিসাব মোতাবেক সংশ্লিষ্ট ব্যাচ নির্ধারিত হয় (যেমন: ২০০৮ সাল = ৬৫তম ব্যাচ)।',
    order: 2,
    is_active: true,
  },
  {
    id: 'faq-3',
    category: 'Entry Pass & Verification',
    question_en: 'How do I receive and verify my Digital Entry Pass?',
    question_bn: 'ডিজিটাল এন্ট্রি পাস কীভাবে পাব এবং যাচাই করব?',
    answer_en: 'Upon successful registration and fee settlement, an encrypted Token Code and digital entry pass with QR code are instantly generated. You can download and print the pass anytime from your Member Portal or verify it via the "Verify Pass" tool.',
    answer_bn: 'নিবন্ধন ও ফি পরিশোধ সম্পন্ন হওয়ার সাথে সাথেই কিউআর কোডসহ একটি ডিজিটাল প্রবেশপত্র তৈরি হয়। আপনি সদস্য পোর্টাল থেকে এটি ডাউনলোড করতে পারবেন অথবা মূল মেনুর "পাস যাচাই" অপশন থেকে কোড দিয়ে তাৎক্ষণিক নিশ্চিত হতে পারবেন।',
    order: 3,
    is_active: true,
  },
  {
    id: 'faq-4',
    category: 'Payment Methods',
    question_en: 'What payment options are available?',
    question_bn: 'কী কী মাধ্যমে নিবন্ধন ফি পরিশোধ করা যাবে?',
    answer_en: 'You can pay online via bKash, Nagad, Rocket, credit/debit cards (SSLCommerz), or visit any authorized offline registration booth in Nanupur, Chattogram, or Dhaka.',
    answer_bn: 'বিকাশ, নগদ, রকেট এবং যেকোনো ব্যাংকের ডেবিট/ক্রেডিট কার্ডের মাধ্যমে অনলাইনে সহজেই ফি পরিশোধ করা যাবে। এছাড়া নির্ধারিত অফলাইন বুথে সরাসরি নগদ প্রদান করে নিবন্ধন করা যাবে।',
    order: 4,
    is_active: true,
  },
];

export const INITIAL_NEWS_POSTS: any[] = [
  {
    id: 'news-1',
    slug: 'anniversary-registration-launched-online',
    title_en: 'Alumni Association Launches Digital Portal for 85th Anniversary Registration',
    title_bn: '৮৫ বছর পূর্তি উৎসবের ডিজিটাল নিবন্ধন পোর্টাল চালু করল প্রাক্তন শিক্ষার্থী পরিষদ',
    content_en: 'The Alumni Association of Nanupur Abu Sobhan High School has officially introduced the online registration portal with automated batch verification, instant mobile banking payments (bKash, Nagad), and unique QR-code entry passes.',
    content_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ স্বয়ংক্রিয় ব্যাচ নির্ধারণ, মোবাইল ব্যাংকিং (বিকাশ, নগদ) পেমেন্ট এবং কিউআর কোড সম্বলিত প্রবেশপত্র সহ পূর্ণাঙ্গ ডিজিটাল নিবন্ধন পোর্টাল চালু করেছে।',
    category: 'Event Updates',
    author: 'IT & Media Wing',
    publish_date: '2026-03-05',
    is_published: true,
    views: 1240,
    featured_image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'news-2',
    slug: 'school-grounds-renovation-underway',
    title_en: 'Historic School Pavilion and Sports Grounds Prepared for Grand Celebration',
    title_bn: '৮৫ বছর পূর্তি উপলক্ষে ঐতিহাসিক স্কুল মাঠ ও প্রাঙ্গণ সজ্জিতকরণ',
    content_en: 'Preparations are actively underway on the campus to welcome over 4,000 alumni and guests for a memorable day of nostalgia, cultural performances, and networking.',
    content_bn: 'ঐতিহাসিক দিনটিকে স্মরণীয় করে রাখতে ক্যাম্পাস প্রাঙ্গণ সংস্কার এবং ৪,০০০ এর অধিক প্রাক্তন শিক্ষার্থী ও অতিথিদের বরণ করতে জোর প্রস্তুতি চলছে।',
    category: 'Campus News',
    author: 'Press Committee',
    publish_date: '2026-02-28',
    is_published: true,
    views: 890,
    featured_image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80'
  }
];

