import {
  Batch,
  CommitteeMember,
  Committee,
  CommitteeMemberItem,
  CommitteeDesignation,
  OfflineRegistrationCenter,
  EventItem,
  Notice,
  NewsPost,
  SchoolInfo,
  AssociationInfo,
  GlobalSettings,
  HeaderConfig,
  TopBarConfig,
  NavigationMenuItem,
  FooterConfig,
  CMSPage,
  FAQItem,
  PaymentGatewayConfig,
  RegistrationConfig,
  TokenFormatConfig,
  BatchConfig,
  CustomRole,
  User,
  Registration,
  EntryToken,
  ProgramScheduleSectionConfig,
  RegistrationFieldConfig,
  HeroConfig,
} from '../src/types';

// Batch calculation reference: 2008 = 65th Batch (Batch = 65 + PassingYear - 2008)
export const initialBatchConfig: BatchConfig = {
  reference_year: 2008,
  reference_batch: 65,
  formula_description: 'Standard School Batch Calculation (Internal)',
  naming_format: 'batch_number',
  overrides: [],
};

const getOrdinal = (n: number) => {
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
};

const toBn = (n: number | string) =>
  n.toString().replace(/\d/g, d => '০১২৩৪৫৬৭৮৯'[parseInt(d)]);

export const initialBatches: Batch[] = Array.from({ length: 55 }, (_, i) => {
  const year = 1972 + i;
  const batchNumber = 65 + (year - 2008);
  return {
    id: `batch-${year}`,
    name_en: `${getOrdinal(batchNumber)} Batch (${year})`,
    name_bn: `${toBn(batchNumber)}তম ব্যাচ (${toBn(year)})`,
    passing_year: year,
    batch_number: batchNumber,
    representative_name: year % 5 === 0 ? `Batch Representative (${year})` : undefined,
    representative_phone: year % 5 === 0 ? `01812${year}00` : undefined,
    registration_count: year === 2008 ? 34 : year === 2005 ? 18 : year === 1995 ? 24 : year === 2012 ? 22 : 6,
    is_active: true,
  };
});

export const initialEvent: EventItem = {
  id: 'event-85th-anniversary',
  slug: '85th-anniversary-reunion',
  title_en: '85th Anniversary Celebration & Grand Alumni Reunion',
  title_bn: '৮৫ বছর পূর্তি উৎসব ও প্রাক্তন শিক্ষার্থী পুনর্মিলনী',
  tagline_en: '85 Years of Heritage, Friendship & Memories (1942 - 2027)',
  tagline_bn: '৮৫ বছরের ঐতিহ্য, বন্ধুত্ব ও স্মৃতির মেলবন্ধন (১৯৪২ - ২০২৭)',
  description_en: 'Celebrate 85 glorious years of Nanupur Abu Sobhan High School with thousands of alumni, revered teachers, and distinguished guests on our historic school grounds in Fatikchhari, Chattogram.',
  description_bn: 'ঐতিহ্যবাহী নানুপুর আবু সোবহান উচ্চ বিদ্যালয়ের গৌরবময় ৮৫ বছর পূর্তি উপলক্ষে প্রিয় প্রাঙ্গণে মিলিত হোন হাজারো প্রাক্তন শিক্ষার্থী ও শিক্ষকদের সাথে।',
  event_date: '2027-01-16',
  start_time: '08:30 AM',
  end_time: '09:00 PM',
  venue_en: 'Nanupur Abu Sobhan High School Premises, Fatikchhari, Chattogram',
  venue_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাঙ্গণ, ফটিকছড়ি, চট্টগ্রাম',
  registration_fee: 1000,
  currency: 'BDT',
  registration_start: '2026-01-01',
  registration_end: '2026-12-31',
  max_capacity: 5000,
  status: 'upcoming',
  banner_image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1600&q=80',
  terms_en: 'Digital entry pass is mandatory for entry. Registration fee includes commemorative kit, breakfast, grand banquet lunch, evening tea, and cultural evening admission.',
  terms_bn: 'প্রবেশদ্বারে অবশ্যই ডিজিটাল প্রবেশ টোকেন দেখাতে হবে। নিবন্ধন ফির মধ্যে স্মরণিকা কিট, প্রাতঃরাশ, মধ্যাহ্নভোজ, সান্ধ্যকালীন নাশতা এবং জমকালো সাংস্কৃতিক অনুষ্ঠান অন্তর্ভুক্ত।'
};

export const initialGlobalSettings: GlobalSettings = {
  site_name_en: 'Nanupur Abu Sobhan High School Alumni Association',
  site_name_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ',
  site_tagline_en: '85 Years of Heritage, Friendship & Memories',
  site_tagline_bn: '৮৫ বছরের ঐতিহ্য, বন্ধুত্ব ও স্মৃতির মেলবন্ধন',
  site_description_en: 'Official alumni management and 85th anniversary celebration portal for Nanupur Abu Sobhan High School, Fatikchhari, Chattogram.',
  site_description_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ ও ৮৫ বছর পূর্তি পুনর্মিলনী ২০২৭ এর অফিসিয়াল ডিজিটাল প্ল্যাটফর্ম।',
  logo_url: '/assets/nash-logo.png',
  mobile_logo_url: '/assets/nash-logo-sm.png',
  favicon_url: '/favicon.ico',
  default_language: 'bn',
  available_languages: ['bn', 'en'],
  copyright_en: '© 2027 Nanupur Abu Sobhan High School Alumni Association. All rights reserved.',
  copyright_bn: '© ২০২৭ নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ। সর্বস্বত্ব সংরক্ষিত।',
  address_en: 'Nanupur, Fatikchhari, Chattogram 4350, Bangladesh',
  address_bn: 'নানুপুর, ফটিকছড়ি, চট্টগ্রাম ৪৩৫০, বাংলাদেশ',
  contact_phone: '+880 1819-123456',
  contact_email: 'info@nanupuralumni.org',
  google_maps_url: 'https://maps.google.com/?q=Nanupur+Abu+Sobhan+High+School',
  office_hours_en: 'Saturday to Thursday: 09:00 AM - 05:00 PM',
  office_hours_bn: 'শনিবার থেকে বৃহস্পতিবার: সকাল ৯:০০ টা - বিকাল ৫:০০ টা',
  primary_color: '#0f4d2a', // Forest green inspired by event identity
  secondary_color: '#d4af37', // Gold / amber accent
  accent_color: '#b91c1c', // Crimson red accent
  background_color: '#f8fafc',
  font_family: 'Hind Siliguri, Plus Jakarta Sans, sans-serif',
  seo_default_title: 'NASH Alumni Association & 85th Anniversary Reunion 2027',
  seo_meta_description: 'Register online for the 85th Anniversary Celebration of Nanupur Abu Sobhan High School (16 Jan 2027). Instant bKash/Nagad payment & secure QR entry pass.',
  seo_og_image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
  search_engine_indexing: true,
  robots_txt: 'User-agent: *\nAllow: /',
  social_links: {
    facebook: 'https://facebook.com/nashalumni',
    youtube: 'https://youtube.com/@nashalumni',
    twitter: 'https://twitter.com/nashalumni',
    linkedin: 'https://linkedin.com/company/nash-alumni',
    instagram: 'https://instagram.com/nashalumni',
  },
};

export const initialTopBarConfig: TopBarConfig = {
  is_enabled: true,
  announcement_en: '📢 85th Anniversary Reunion on Saturday, 16 January 2027 — Online Registration is Open!',
  announcement_bn: '📢 ৮৫ বছর পূর্তি পুনর্মিলনী: আগামী ১৬ জানুয়ারি ২০২৭, শনিবার — অনলাইন নিবন্ধন চলছে!',
  show_notice_indicator: true,
  show_contact_info: true,
  contact_phone: '+880 1819-123456',
  contact_email: 'reunion2027@nanupuralumni.org',
  show_login_link: true,
  show_registration_link: true,
  show_language_selector: true,
  show_social_icons: true,
  custom_cta_text_en: 'Register Now',
  custom_cta_text_bn: 'নিবন্ধন করুন',
  custom_cta_url: '#register',
};

export const initialHeaderConfig: HeaderConfig = {
  logo_url: '',
  mobile_logo_url: '',
  logo_link: '/',
  show_search: false,
  show_cta_button: true,
  cta_text_en: 'Register for Reunion',
  cta_text_bn: 'পুনর্মিলনী নিবন্ধন',
  cta_url: '#register',
  show_language_switcher: true,
  show_user_menu: true,
};

export const initialMenus: NavigationMenuItem[] = [
  {
    id: 'menu-home',
    label_en: 'Home',
    label_bn: 'মূলপাতা',
    url: '/',
    target: '_self',
    order: 1,
    is_active: true,
  },
  {
    id: 'menu-about',
    label_en: 'About',
    label_bn: 'পরিচিতি',
    url: '#about',
    target: '_self',
    order: 2,
    is_active: true,
    children: [
      {
        id: 'menu-about-school',
        label_en: 'School Heritage (Est. 1942)',
        label_bn: 'বিদ্যালয়ের ঐতিহ্য (স্থাপিত ১৯৪২)',
        url: '#school',
        target: '_self',
        order: 1,
        parent_id: 'menu-about',
        is_active: true,
      },
      {
        id: 'menu-about-association',
        label_en: 'Alumni Association',
        label_bn: 'প্রাক্তন শিক্ষার্থী পরিষদ',
        url: '#association',
        target: '_self',
        order: 2,
        parent_id: 'menu-about',
        is_active: true,
      },
      {
        id: 'menu-about-committee',
        label_en: 'Executive Committee',
        label_bn: 'কার্যনির্বাহী পরিষদ',
        url: '#committee',
        target: '_self',
        order: 3,
        parent_id: 'menu-about',
        is_active: true,
      },
      {
        id: 'menu-about-history',
        label_en: 'Reunion History',
        label_bn: 'পুনর্মিলনীর ইতিহাস',
        url: '#history',
        target: '_self',
        order: 4,
        parent_id: 'menu-about',
        is_active: true,
      },
    ],
  },
  {
    id: 'menu-notices',
    label_en: 'Notices & Circulars',
    label_bn: 'বিজ্ঞপ্তি',
    url: '#notices',
    target: '_self',
    order: 3,
    is_active: true,
  },
  {
    id: 'menu-news',
    label_en: 'News & Updates',
    label_bn: 'খবর ও আপডেট',
    url: '#news',
    target: '_self',
    order: 4,
    is_active: true,
  },
  {
    id: 'menu-faq',
    label_en: 'FAQ',
    label_bn: 'সাধারণ জিজ্ঞাসা',
    url: '#faq',
    target: '_self',
    order: 5,
    is_active: true,
  },
  {
    id: 'menu-contact',
    label_en: 'Contact',
    label_bn: 'যোগাযোগ',
    url: '#contact',
    target: '_self',
    order: 6,
    is_active: true,
  },
];

export const initialFooterConfig: FooterConfig = {
  logo_url: '',
  description_en: 'Nanupur Abu Sobhan High School Alumni Association connects thousands of proud alumni worldwide, uniting generations in celebration of our heritage.',
  description_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ—বিশ্বজুড়ে সকল প্রাক্তন শিক্ষার্থীদের ঐক্য ও মেলবন্ধনের কেন্দ্রীয় প্ল্যাটফর্ম।',
  address_en: 'Nanupur, Fatikchhari, Chattogram 4350, Bangladesh',
  address_bn: 'নানুপুর, ফটিকছড়ি, চট্টগ্রাম ৪৩৫০, বাংলাদেশ',
  phone: '+880 1819-123456',
  email: 'info@nanupuralumni.org',
  copyright_en: '© 2027 Nanupur Abu Sobhan High School Alumni Association. All rights reserved.',
  copyright_bn: '© ২০২৭ নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ। সর্বস্বত্ব সংরক্ষিত।',
  social_links: {
    facebook: 'https://facebook.com/nashalumni',
    youtube: 'https://youtube.com/@nashalumni',
    twitter: 'https://twitter.com/nashalumni',
    linkedin: 'https://linkedin.com/company/nash-alumni',
  },
  columns: [
    {
      id: 'col-explore',
      title_en: 'Explore NASH',
      title_bn: 'অনুসন্ধান',
      order: 1,
      is_active: true,
      links: [
        { id: 'link-1', label_en: 'About School', label_bn: 'বিদ্যালয় পরিচিতি', url: '#school', target: '_self', order: 1, is_active: true },
        { id: 'link-2', label_en: 'Alumni Association', label_bn: 'প্রাক্তন শিক্ষার্থী পরিষদ', url: '#association', target: '_self', order: 2, is_active: true },
        { id: 'link-3', label_en: 'Executive Committee', label_bn: 'কার্যনির্বাহী পরিষদ', url: '#committee', target: '_self', order: 3, is_active: true },
        { id: 'link-4', label_en: '85th Anniversary Event', label_bn: '৮৫ বছর পূর্তি উৎসব', url: '#event-details', target: '_self', order: 4, is_active: true },
      ],
    },
    {
      id: 'col-services',
      title_en: 'Alumni Services',
      title_bn: 'সেবাসমূহ',
      order: 2,
      is_active: true,
      links: [
        { id: 'link-5', label_en: 'Reunion Registration', label_bn: 'পুনর্মিলনী নিবন্ধন', url: '#register', target: '_self', order: 1, is_active: true },
        { id: 'link-6', label_en: 'Verify Entry Pass', label_bn: 'প্রবেশ পাস যাচাই', url: '#verify', target: '_self', order: 2, is_active: true },
        { id: 'link-7', label_en: 'Batch Directory', label_bn: 'ব্যাচ ডিরেক্টরি', url: '#batches', target: '_self', order: 3, is_active: true },
        { id: 'link-8', label_en: 'Official Circulars', label_bn: 'অফিসিয়াল বিজ্ঞপ্তি', url: '#notices', target: '_self', order: 4, is_active: true },
      ],
    },
    {
      id: 'col-help',
      title_en: 'Help & Support',
      title_bn: 'সহায়তা ও যোগাযোগ',
      order: 3,
      is_active: true,
      links: [
        { id: 'link-9', label_en: 'Frequently Asked Questions', label_bn: 'সাধারণ জিজ্ঞাসা (FAQ)', url: '#faq', target: '_self', order: 1, is_active: true },
        { id: 'link-10', label_en: 'Payment Helpdesk', label_bn: 'পেমেন্ট হেল্পডেস্ক', url: '#contact', target: '_self', order: 2, is_active: true },
        { id: 'link-11', label_en: 'Terms & Conditions', label_bn: 'শর্তাবলী ও নীতিমালা', url: '#terms', target: '_self', order: 3, is_active: true },
        { id: 'link-12', label_en: 'Contact & Support', label_bn: 'যোগাযোগ ও তথ্য', url: '#contact', target: '_self', order: 4, is_active: true },
      ],
    },
  ],
};

export const initialFAQs: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Registration & Fees',
    question_en: 'How much is the registration fee for the 85th Anniversary Celebration?',
    question_bn: '৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনীর নিবন্ধন ফি কত?',
    answer_en: 'The registration fee is BDT 1,000 per alumnus. It covers the commemorative anniversary bag, registration kit, celebration badge, souvenir book, breakfast, grand luncheon banquet, evening tea, and cultural event entry.',
    answer_bn: 'প্রতিজন প্রাক্তন শিক্ষার্থীর নিবন্ধন ফি ১,০০০ টাকা। এর মধ্যে রয়েছে স্মরণিকা ব্যাগ, মেডেল/ব্যাজ, স্মরণিকা বই, প্রাতঃরাশ, মধ্যাহ্নভোজ, সান্ধ্যকালীন নাশতা এবং জমকালো সাংস্কৃতিক অনুষ্ঠান।',
    order: 1,
    is_active: true,
  },
  {
    id: 'faq-2',
    category: 'Batch Information',
    question_en: 'How is my batch number determined?',
    question_bn: 'আমার ব্যাচ নম্বর কীভাবে নির্ধারিত হবে?',
    answer_en: 'Your batch is automatically assigned based on your SSC / Matriculation passing year as recorded in the official school archives. Each passing year corresponds to an honored alumni batch.',
    answer_bn: 'আপনার এসএসসি / ম্যাট্রিকুলেশন পাসের সাল অনুযায়ী বিদ্যালয়ের প্রাতিষ্ঠানিক রেকর্ড মোতাবেক আপনার সংশ্লিষ্ট ব্যাচ নির্ধারিত হয়। প্রতিটি পাসের সাল একটি স্বতন্ত্র সম্মানিত ব্যাচ হিসেবে পরিগণিত।',
    order: 2,
    is_active: true,
  },
  {
    id: 'faq-3',
    category: 'Payments',
    question_en: 'Which payment methods are accepted for online registration?',
    question_bn: 'অনলাইন নিবন্ধনের জন্য কোন কোন পেমেন্ট মাধ্যম ব্যবহার করা যাবে?',
    answer_en: 'We accept instant mobile banking via bKash, Nagad, and Rocket, as well as Visa, Mastercard, and internet banking via SSLCommerz. All transactions are securely verified with instant token issuance.',
    answer_bn: 'বিকাশ, নগদ, রকেটের মতো মোবাইল ব্যাংকিং এবং ভিসা, মাস্টারকার্ড ও অনলাইন ব্যাংকিংয়ের মাধ্যমে নিরাপদে ফি পরিশোধ করা যাবে। পেমেন্ট সম্পন্ন হওয়ার সাথে সাথেই ডিজিটাল পাস ইস্যু হবে।',
    order: 3,
    is_active: true,
  },
  {
    id: 'faq-4',
    category: 'Entry Pass & Token',
    question_en: 'What is the digital entry pass and how do I receive it?',
    question_bn: 'ডিজিটাল প্রবেশ পাস কী এবং আমি এটি কীভাবে পাব?',
    answer_en: 'Upon successful fee payment, a cryptographically secure, high-entropy Entry Pass with a unique QR code is generated instantly. You can download it to your mobile, print it, or view it at any time in the Member Portal.',
    answer_bn: 'পেমেন্ট সম্পন্ন হওয়ামাত্রই ইউনিক কিউআর কোড সম্বলিত একটি নিরাপদ ডিজিটাল প্রবেশ পাস তৈরি হবে। আপনি এটি ফোনে সংরক্ষণ করতে পারবেন, প্রিন্ট করতে পারবেন অথবা সদস্য পোর্টালে লগইন করে দেখতে পারবেন।',
    order: 4,
    is_active: true,
  },
  {
    id: 'faq-5',
    category: 'Event Day',
    question_en: 'When and where will the celebration take place?',
    question_bn: 'অনুষ্ঠানটি কখন ও কোথায় অনুষ্ঠিত হবে?',
    answer_en: 'The event will take place on Saturday, 16 January 2027 from 08:30 AM to 09:00 PM at the Nanupur Abu Sobhan High School premises in Fatikchhari, Chattogram.',
    answer_bn: 'উৎসবটি আগামী ১৬ জানুয়ারি ২০২৭, শনিবার সকাল ৮:৩০ টা থেকে রাত ৯:০০ টা পর্যন্ত নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাঙ্গণে অনুষ্ঠিত হবে।',
    order: 5,
    is_active: true,
  },
];

export const initialPaymentGateways: PaymentGatewayConfig[] = [
  {
    id: 'gw-bkash',
    code: 'bkash',
    name: 'bKash MFS',
    display_name_en: 'bKash Payment',
    display_name_bn: 'বিকাশ পেমেন্ট',
    is_enabled: true,
    is_test_mode: true,
    merchant_id: 'NASH_BKASH_01',
    store_id: 'BKASH_STORE_101',
    currency: 'BDT',
    transaction_prefix: 'BK',
    sort_order: 1,
    icon_url: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=100&q=80',
    instructions_en: 'Instant checkout via bKash mobile financial services.',
    instructions_bn: 'বিকাশ মোবাইল ব্যাংকিংয়ের মাধ্যমে তাৎক্ষণিক পেমেন্ট সম্পন্ন করুন।',
  },
  {
    id: 'gw-nagad',
    code: 'nagad',
    name: 'Nagad Digital Financial Service',
    display_name_en: 'Nagad Payment',
    display_name_bn: 'নগদ পেমেন্ট',
    is_enabled: true,
    is_test_mode: true,
    merchant_id: 'NASH_NAGAD_01',
    currency: 'BDT',
    transaction_prefix: 'NG',
    sort_order: 2,
    instructions_en: 'Pay via Nagad digital payment system.',
    instructions_bn: 'ডাক বিভাগের ডিজিটাল লেনদেন নগদ-এর মাধ্যমে পেমেন্ট সম্পন্ন করুন।',
  },
  {
    id: 'gw-rocket',
    code: 'rocket',
    name: 'Rocket (Dutch-Bangla Bank)',
    display_name_en: 'Rocket Mobile Banking',
    display_name_bn: 'রকেট পেমেন্ট',
    is_enabled: true,
    is_test_mode: true,
    currency: 'BDT',
    transaction_prefix: 'RK',
    sort_order: 3,
    instructions_en: 'Pay securely using DBBL Rocket account.',
    instructions_bn: 'ডাচ-বাংলা ব্যাংক রকেটের মাধ্যমে ফি প্রদান করুন।',
  },
  {
    id: 'gw-sslcommerz',
    code: 'sslcommerz',
    name: 'SSLCommerz Gateway',
    display_name_en: 'Debit/Credit Cards & NetBanking',
    display_name_bn: 'কার্ড ও ইন্টারনেট ব্যাংকিং (SSLCommerz)',
    is_enabled: true,
    is_test_mode: true,
    store_id: 'nash_ssl_store',
    currency: 'BDT',
    transaction_prefix: 'SSL',
    sort_order: 4,
    instructions_en: 'Visa, MasterCard, Amex, and internet banking channels.',
    instructions_bn: 'ভিসা, মাস্টারকার্ড বা অন্যান্য কার্ডের মাধ্যমে অনলাইনে ফি দিন।',
  },
];

export const initialRegistrationFields: RegistrationFieldConfig[] = [
  {
    id: 'field_full_name',
    name: 'full_name',
    label_en: 'Full Name',
    label_bn: 'পূর্ণ নাম',
    placeholder_en: 'e.g. Mohammad Rafiqul Islam',
    placeholder_bn: 'যেমন: মোহাম্মদ রফিকুল ইসলাম',
    help_text_en: 'As per academic certificates or National ID',
    help_text_bn: 'সনদপত্র অথবা জাতীয় পরিচয়পত্র অনুযায়ী',
    type: 'text',
    is_required: true,
    is_enabled: true,
    order: 1,
    grid_span: 'full',
    validation_rule: 'required|min:3',
  },
  {
    id: 'field_dob',
    name: 'dob',
    label_en: 'Date of Birth',
    label_bn: 'জন্ম তারিখ',
    type: 'date',
    is_required: true,
    is_enabled: true,
    order: 2,
    grid_span: 'half',
    validation_rule: 'required',
  },
  {
    id: 'field_gender',
    name: 'gender',
    label_en: 'Gender',
    label_bn: 'লিঙ্গ',
    type: 'select',
    is_required: true,
    is_enabled: true,
    order: 3,
    options: ['male', 'female', 'other'],
    options_bn: ['পুরুষ', 'মহিলা', 'অন্যান্য'],
    grid_span: 'half',
    validation_rule: 'required',
  },
  {
    id: 'field_passing_year',
    name: 'passing_year',
    label_en: 'Passing / SSC Year',
    label_bn: 'পাসের বছর / এসএসসি সাল',
    placeholder_en: 'e.g. 2005',
    placeholder_bn: 'যেমন: ২০০৫',
    help_text_en: 'Year you completed SSC or studied at Nanupur High School',
    help_text_bn: 'যে সালে বিদ্যালয় ত্যাগ বা এসএসসি উত্তীর্ণ হয়েছিলেন',
    type: 'number',
    is_required: true,
    is_enabled: true,
    order: 4,
    grid_span: 'half',
    validation_rule: 'required|min:1942|max:2035',
  },
  {
    id: 'field_phone',
    name: 'phone',
    label_en: 'Mobile Number',
    label_bn: 'মোবাইল নম্বর',
    placeholder_en: '018XXXXXXXX',
    placeholder_bn: '০১৮XXXXXXXX',
    help_text_en: 'Active mobile number to receive confirmation & entry pass',
    help_text_bn: 'এসএমএস ও প্রবেশ টোকেন কোড পেতে সচল নম্বর দিন',
    type: 'tel',
    is_required: true,
    is_enabled: true,
    order: 5,
    grid_span: 'half',
    validation_rule: 'required|phone',
  },
  {
    id: 'field_blood_group',
    name: 'blood_group',
    label_en: 'Blood Group',
    label_bn: 'রক্তের গ্রুপ',
    type: 'select',
    is_required: false,
    is_enabled: true,
    order: 6,
    options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    grid_span: 'half',
  },
  {
    id: 'field_t_shirt_size',
    name: 't_shirt_size',
    label_en: 'T-Shirt Size',
    label_bn: 'টি-শার্টের সাইজ',
    placeholder_en: 'Select size (M, L, XL, XXL, XXXL)',
    placeholder_bn: 'সাইজ নির্বাচন করুন',
    help_text_en: 'Commemorative 85th reunion polo shirt size',
    help_text_bn: '৮৫ বছর পূর্তির বিশেষ স্মারক টি-শার্টের সাইজ',
    type: 'select',
    is_required: true,
    is_enabled: true,
    order: 7,
    options: ['M', 'L', 'XL', 'XXL', 'XXXL'],
    options_bn: ['M (মিডিয়াম)', 'L (লার্জ)', 'XL (এক্সট্রা লার্জ)', 'XXL (ডাবল এক্সেল)', 'XXXL (ট্রিপল এক্সেল)'],
    grid_span: 'half',
    validation_rule: 'required|in:M,L,XL,XXL,XXXL',
  },
  {
    id: 'field_email',
    name: 'email',
    label_en: 'Email Address',
    label_bn: 'ইমেইল ঠিকানা',
    placeholder_en: 'alumni@example.com',
    placeholder_bn: 'alumni@example.com',
    type: 'email',
    is_required: false,
    is_enabled: true,
    order: 8,
    grid_span: 'half',
    validation_rule: 'email',
  },
  {
    id: 'field_occupation',
    name: 'occupation',
    label_en: 'Profession / Designation',
    label_bn: 'পেশা ও পদবি',
    placeholder_en: 'e.g. Senior Software Engineer / Business Owner',
    placeholder_bn: 'যেমন: সিনিয়র শিক্ষক / প্রকৌশলী / ব্যবসায়ী',
    type: 'text',
    is_required: false,
    is_enabled: true,
    order: 9,
    grid_span: 'half',
  },
  {
    id: 'field_address',
    name: 'address',
    label_en: 'Current Address / City',
    label_bn: 'বর্তমান ঠিকানা / শহর',
    placeholder_en: 'e.g. Chattogram / Dhaka / Abroad',
    placeholder_bn: 'যেমন: চট্টগ্রাম / ঢাকা / প্রবাস',
    type: 'text',
    is_required: false,
    is_enabled: true,
    order: 10,
    grid_span: 'full',
  },
  {
    id: 'field_photo_url',
    name: 'photo_url',
    label_en: 'Photograph',
    label_bn: 'ছবি',
    help_text_en: 'Passport size photo for souvenir book & entry pass',
    help_text_bn: 'স্মরণিকা গ্রন্থ ও ডিজিটাল প্রবেশপত্রের জন্য ছবি আপলোড করুন',
    type: 'file',
    is_required: false,
    is_enabled: true,
    order: 11,
    grid_span: 'full',
  },
];

export const initialProgramSchedule: ProgramScheduleSectionConfig = {
  is_enabled: true,
  badge_en: 'Official Event Program • 16 January 2027',
  badge_bn: '১৬ জানুয়ারি ২০২৭ • সারাদিনব্যাপী বর্ণাঢ্য আয়োজন',
  title_en: 'Day-Long Festivities & Program Schedule',
  title_bn: 'পুনর্মিলনী উৎসবের সূচি ও আকর্ষণ',
  subtitle_en: 'Immerse in an enriching day filled with joyful memories, traditional dining, honoring mentors, and cultural melodies.',
  subtitle_bn: 'সকাল থেকে রাত অবধি স্মৃতিচারণ, মেজবান, সাংস্কৃতিক অনুষ্ঠান ও প্রীতি আড্ডায় ভরপুর দিন।',
  items: [
    {
      id: 'sched-1',
      time: '08:30 AM',
      title_en: 'Registration Kit & Souvenir Gift',
      title_bn: 'কিট ও স্মরণিকা বিতরণ',
      description_en: 'Present your QR token pass to collect the commemorative bag, custom polo, 85th Souvenir book, and badge.',
      description_bn: 'ডিজিটাল প্রবেশপত্র স্ক্যান করে গ্রহণ করুন বিশেষ স্মারক ব্যাগ, টি-শার্ট, ক্যাপ ও ৮৫তম বর্ষের স্মরণিকা গ্রন্থ।',
      icon: 'gift',
      order: 1,
      is_active: true,
    },
    {
      id: 'sched-2',
      time: '10:00 AM',
      title_en: 'Heritage Rally & Flag Ceremony',
      title_bn: 'আনন্দ শোভাযাত্রা ও উদ্বোধন',
      description_en: 'Grand opening ceremony, flag hoisting, and alumni rally honoring our historic corridors and village pride.',
      description_bn: 'জাতীয় সংগীত পরিবেশন, পতাকা উত্তোলন এবং নানুপুর বাজার প্রদক্ষিণ করে বর্ণাঢ্য আনন্দ শোভাযাত্রা।',
      icon: 'users',
      order: 2,
      is_active: true,
    },
    {
      id: 'sched-3',
      time: '11:30 AM',
      title_en: 'Reminiscence & Teacher Honors',
      title_bn: 'স্মৃতিচারণ ও শিক্ষক সম্মাননা',
      description_en: 'Honoring our revered mentors and teachers with commemorative crests and touching reminiscences.',
      description_bn: 'শ্রদ্ধেয় শিক্ষক-শিক্ষিকাদের বিশেষ উত্তরীয় ও স্মারক সম্মাননা প্রদান এবং প্রবীণ প্রাক্তনীদের স্মৃতিচারণ পর্ব।',
      icon: 'award',
      order: 3,
      is_active: true,
    },
    {
      id: 'sched-4',
      time: '01:30 PM',
      title_en: 'Traditional Mezban Banquet',
      title_bn: 'ঐতিহ্যবাহী মেজবানি ভোজ',
      description_en: 'Savor authentic Chattogram culinary heritage with a grand traditional Mezban feast.',
      description_bn: 'চট্টগ্রামের সুস্বাদু ঐতিহ্যবাহী মেজবানি মাংস, ডাল ও ভাত পরিবেশন (বিশেষ নিরামিষাশী ব্যবস্থাসহ)।',
      icon: 'utensils',
      order: 4,
      is_active: true,
    },
    {
      id: 'sched-5',
      time: '03:30 PM',
      title_en: 'Batch Photo Sessions & Networking',
      title_bn: 'ব্যাচভিত্তিক আড্ডা ও ছবি',
      description_en: 'Capture historic reunion memories at the dedicated batch photography zones and reconnect with batchmates.',
      description_bn: 'সুসজ্জিত ফটোবুথে সহপাঠীদের সাথে ব্যাচভিত্তিক গ্রুপ ফটোসেশন এবং আজীবন সদস্যপদ নেটওয়ার্কিং।',
      icon: 'heart',
      order: 5,
      is_active: true,
    },
    {
      id: 'sched-6',
      time: '05:30 PM',
      title_en: 'Grand Cultural Night & Concert',
      title_bn: 'মহতী সাংস্কৃতিক সন্ধ্যা ও কনসার্ট',
      description_en: 'Spectacular musical concert, regional folk songs, drama presentation, and celebration fireworks.',
      description_bn: 'বিদ্যালয়ের প্রাক্তন ও জাতীয় শিল্পীদের পরিবেশনায় দেশাত্মবোধক গান, চাটগাঁইয়া আঞ্চলিক সঙ্গীত ও মনোজ্ঞ আতশবাজি।',
      icon: 'music',
      order: 6,
      is_active: true,
    },
  ],
};

export const initialRegistrationConfig: RegistrationConfig = {
  is_enabled: true,
  start_date: '2026-01-01',
  end_date: '2026-12-31',
  fee_amount: 1000,
  currency: 'BDT',
  event_id: 'event-85th-anniversary',
  max_capacity: 5000,
  terms_en: 'I certify that the information provided is accurate and I agree to adhere to the code of conduct during the celebration.',
  terms_bn: 'আমি প্রত্যয়ন করছি যে প্রদত্ত তথ্য সত্য ও সঠিক এবং উৎসব চলাকালে শৃঙ্খলা বজায় রাখতে অঙ্গীকারাবদ্ধ।',
  instructions_en: 'Fill in your personal details accurately to register for the 85th Anniversary Grand Reunion celebration.',
  instructions_bn: '৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনীতে অংশগ্রহণের জন্য সঠিক তথ্য প্রদান করে নিবন্ধন সম্পন্ন করুন।',
  success_message_en: 'Your registration is confirmed! Download your Entry Pass below.',
  success_message_bn: 'আপনার নিবন্ধন সফল হয়েছে! নিচে আপনার ডিজিটাল প্রবেশ পাস ডাউনলোড করুন।',
  fields: initialRegistrationFields,
};

export const initialTokenFormatConfig: TokenFormatConfig = {
  prefix: 'NASHS',
  separator: '-',
  use_batch_number: true,
  batch_placeholder: '[Batch Number]',
  serial_placeholder: '[Registration Serial]',
  starting_number: 1,
  padding_length: 4,
  reset_per_batch: true,
  is_active: true,
  format_pattern: 'NASHS-[Batch Number]-[Registration Serial]',
};

export const initialRoles: CustomRole[] = [
  {
    id: 'role-super-admin',
    name: 'Super Admin',
    description: 'Full uninhibited system and administrative control.',
    permissions: [
      'pages.view', 'pages.create', 'pages.edit', 'pages.delete',
      'users.view', 'users.create', 'users.edit', 'users.delete',
      'events.view', 'events.create', 'events.edit', 'events.delete',
      'registrations.view', 'registrations.edit', 'registrations.export',
      'payments.view', 'payments.manage', 'payments.refund',
      'tokens.view', 'tokens.verify', 'tokens.revoke',
      'settings.view', 'settings.manage',
      'menus.view', 'menus.manage',
      'faq.view', 'faq.manage',
    ],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-admin',
    name: 'Administrator',
    description: 'Day-to-day administrative management access.',
    permissions: [
      'pages.view', 'pages.create', 'pages.edit',
      'users.view', 'users.edit',
      'events.view', 'events.edit',
      'registrations.view', 'registrations.edit', 'registrations.export',
      'payments.view', 'payments.manage',
      'tokens.view', 'tokens.verify',
      'settings.view',
      'menus.view', 'menus.manage',
      'faq.view', 'faq.manage',
    ],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-content-manager',
    name: 'Content Manager',
    description: 'Manages website content: pages, notices, news, media, FAQ, and menus.',
    permissions: [
      'pages.view', 'pages.create', 'pages.edit', 'pages.delete',
      'menus.view', 'menus.manage',
      'faq.view', 'faq.manage',
      'settings.view',
    ],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-event-manager',
    name: 'Event Manager',
    description: 'Oversees registration records, batch quotas, entry tokens, and gate check-in.',
    permissions: [
      'events.view', 'events.edit',
      'registrations.view', 'registrations.edit', 'registrations.export',
      'tokens.view', 'tokens.verify',
    ],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-finance-manager',
    name: 'Finance & Payment Manager',
    description: 'Monitors transactions, gateway statuses, reconciliations, and financial audits.',
    permissions: [
      'payments.view', 'payments.manage',
      'registrations.view',
    ],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-moderator',
    name: 'Moderator',
    description: 'Community moderation and entry pass scanning privileges.',
    permissions: [
      'tokens.view', 'tokens.verify',
      'registrations.view',
    ],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-alumni-member',
    name: 'Alumni Member',
    description: 'Standard alumnus with personal profile, registration, and entry token access.',
    permissions: [],
    is_system: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const initialUsers: User[] = [
  {
    id: 'user-super-admin',
    username: 'super_admin',
    name: 'Chief Administrator (NASH Secretariat)',
    name_bn: 'প্রধান প্রশাসক (সচিবালয়)',
    email: 'admin@nanupuralumni.org',
    phone: '01819000001',
    role: 'super_admin',
    gender: 'male',
    blood_group: 'B+',
    dob: '1976-01-01',
    passing_year: 1992,
    batch: '49th Batch (1992)',
    status: 'active',
    created_at: '2026-01-01T00:00:00Z',
  }
];

export const initialPages: CMSPage[] = [
  {
    id: 'page-about',
    slug: 'about',
    title_en: 'About 85th Anniversary & Grand Reunion 2027',
    title_bn: '৮৫ বছর পূর্তি উৎসব ও মহা পুনর্মিলনী ২০২৭ সম্পর্কে',
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    sections: [
      {
        id: 'sec-about-hero',
        type: 'hero',
        order: 1,
        is_active: true,
        title_en: 'Celebrating 85 Years of Glorious Heritage',
        title_bn: '৮৫ বছরের গৌরবময় ঐতিহ্যের ঐতিহাসিক পুনর্মিলনী',
        subtitle_en: '1942 – 2027 • Nanupur Abu Sobhan High School Alumni Grand Gathering',
        subtitle_bn: '১৯৪২ – ২০২৭ • নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ',
        image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
      },
      {
        id: 'sec-about-vision',
        type: 'text',
        order: 2,
        is_active: true,
        title_en: 'The Grand Gathering on 16 January 2027',
        title_bn: '১৬ জানুয়ারি ২০২৭-এর ঐতিহাসিক মিলনমেলা',
        content_en: 'On Saturday, 16 January 2027, generations of alumni spanning 85 glorious years will reunite on our beloved campus. From the foundational batches of the 1940s to our latest graduates, this historic celebration brings thousands together to rekindle old bonds, honor legendary teachers, and pledge support for the next century of students.',
        content_bn: 'আগামী ১৬ জানুয়ারি ২০২৭, শনিবার বিদ্যালয়ের চিরসবুজ ক্যাম্পাসে অনুষ্ঠিত হতে যাচ্ছে বহুল প্রতীক্ষিত ৮৫ বছর পূর্তি উৎসব ও মহা পুনর্মিলনী। দেশ-বিদেশের হাজারো প্রাক্তন শিক্ষার্থীর অংশগ্রহণে এই দিনটি হবে স্মৃতিচারণ, সৌহার্দ্য ও ঐক্যের অনন্য মাহেন্দ্রক্ষণ।'
      },
      {
        id: 'sec-about-stats',
        type: 'stats',
        order: 3,
        is_active: true,
        title_en: 'Anniversary Highlights',
        title_bn: 'এক নজরে মহা সম্মেলন',
        meta: {
          stats: [
            { label_en: 'Years of Heritage', label_bn: 'ঐতিহ্যের বছর', value: '85 Years' },
            { label_en: 'Honored Batches', label_bn: 'সম্মানিত ব্যাচ', value: '85+' },
            { label_en: 'Expected Alumni', label_bn: 'প্রত্যাশিত উপস্থিতি', value: '5,000+' },
            { label_en: 'Grand Event Date', label_bn: 'পুনর্মিলনী তারিখ', value: '16 Jan 2027' }
          ]
        }
      },
      {
        id: 'sec-about-cta',
        type: 'cta',
        order: 4,
        is_active: true,
        title_en: 'Register Today and Secure Your Entry Token',
        title_bn: 'আজই নিবন্ধন সম্পন্ন করে ডিজিটাল পাস সংগ্রহ করুন',
        button_text_en: 'Complete Online Registration',
        button_text_bn: 'অনলাইন নিবন্ধন সম্পন্ন করুন',
        button_url: '#register'
      }
    ]
  },
  {
    id: 'page-school',
    slug: 'school-heritage',
    title_en: 'School Heritage & Academic Legacy',
    title_bn: 'বিদ্যালয়ের গৌরবময় ঐতিহ্য ও ইতিবৃত্ত',
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    sections: [
      {
        id: 'sec-1',
        type: 'hero',
        order: 1,
        is_active: true,
        title_en: 'Nanupur Abu Sobhan High School',
        title_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয়',
        subtitle_en: 'Established in 1942 • EIIN: 104321 • Fatikchhari, Chattogram',
        subtitle_bn: 'স্থাপিত: ১৯৪২ খ্রি. • ইআইআইএন: ১০৪৩২১ • ফটিকছড়ি, চট্টগ্রাম',
        image_url: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
      },
      {
        id: 'sec-2',
        type: 'text',
        order: 2,
        is_active: true,
        title_en: 'Historical Background',
        title_bn: 'ঐতিহাসিক পটভূমি',
        content_en: 'Founded in 1942 by the visionary philanthropist Late Alhaj Abu Sobhan, the school was born out of a profound commitment to enlighten the youth of northern Chattogram. Over eighty-five years, it has transformed into a prestigious seat of learning with over 2,000 active students and thousands of proud alumni across the world.',
        content_bn: '১৯৪২ সালে প্রখ্যাত সমাজসেবী মরহুম আলহাজ্ব আবু সোবহানের মহতী উদ্যোগে এই বিদ্যাপীঠ প্রতিষ্ঠিত হয়। উত্তর চট্টগ্রামের শিক্ষা ও সংস্কৃতির অগ্রগতিতে বিদ্যালয়টি বিগত ৮৫ বছর ধরে আলোকবর্তিকা হিসেবে কাজ করে আসছে।',
      },
      {
        id: 'sec-3',
        type: 'stats',
        order: 3,
        is_active: true,
        title_en: 'School at a Glance',
        title_bn: 'এক নজরে বিদ্যালয়',
        meta: {
          stats: [
            { label_en: 'Established', label_bn: 'প্রতিষ্ঠা', value: '1942' },
            { label_en: 'Alumni Batches', label_bn: 'ব্যাচ সংখ্যা', value: '85+' },
            { label_en: 'Current Students', label_bn: 'বর্তমান শিক্ষার্থী', value: '2,200+' },
            { label_en: 'Campus Area', label_bn: 'ক্যাম্পাস আয়তন', value: '5 Acres' },
          ]
        }
      },
      {
        id: 'sec-4',
        type: 'gallery',
        order: 4,
        is_active: true,
        title_en: 'Campus Facilities & Memorabilia',
        title_bn: 'ক্যাম্পাস ও সুযোগ-সুবিধা',
        images: [
          'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80',
          'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80',
          'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&q=80',
        ]
      }
    ]
  },
  {
    id: 'page-association',
    slug: 'alumni-association',
    title_en: 'Alumni Association Mission & Vision',
    title_bn: 'প্রাক্তন শিক্ষার্থী পরিষদের লক্ষ্য ও উদ্দেশ্য',
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    sections: [
      {
        id: 'sec-assoc-1',
        type: 'hero',
        order: 1,
        is_active: true,
        title_en: 'NASH Alumni Association',
        title_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ',
        subtitle_en: 'Uniting 85 Generations of Alumni in Service & Fellowship',
        subtitle_bn: 'ভ্রাতৃত্ব, সৌহার্দ্য ও প্রাতিষ্ঠানিক উন্নয়নে ৮৫ প্রজন্মের মেলবন্ধন',
        image_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
      },
      {
        id: 'sec-assoc-2',
        type: 'text',
        order: 2,
        is_active: true,
        title_en: 'Objectives & Core Mandate',
        title_bn: 'মূল উদ্দেশ্যসমূহ',
        content_en: 'The Alumni Association operates as the sovereign liaison between alumni, current faculty, and the school managing committee. Its pillars include: 1. Unifying all batches into a unified digital ecosystem. 2. Endowing scholarships for underprivileged students. 3. Upgrading science, language, and technology labs. 4. Organizing milestone reunions.',
        content_bn: 'প্রাক্তন শিক্ষার্থী পরিষদ বিদ্যালয়ের টেকসই উন্নয়ন, শিক্ষার্থীদের শিক্ষাবৃত্তি প্রদান এবং সকল ব্যাচের মাঝে আজীবন ভ্রাতৃত্বপূর্ণ যোগাযোগ রক্ষায় কাজ করে যাচ্ছে।',
      },
      {
        id: 'sec-assoc-3',
        type: 'cta',
        order: 3,
        is_active: true,
        title_en: 'Join Your Batch Community Today',
        title_bn: 'আপনার ব্যাচের সাথে যুক্ত হোন',
        button_text_en: 'Register for 85th Anniversary',
        button_text_bn: '৮৫ বছর পূর্তিতে নিবন্ধন করুন',
        button_url: '#register',
      }
    ]
  }
];

export const initialSchoolInfo: SchoolInfo = {
  name_en: 'Nanupur Abu Sobhan High School',
  name_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয়',
  established_year: 1942,
  eiin_number: '104321',
  location_en: 'Nanupur Union, Fatikchhari Upazila, Chattogram District, Bangladesh',
  location_bn: 'নানুপুর ইউনিয়ন, ফটিকছড়ি উপজেলা, চট্টগ্রাম জেলা, বাংলাদেশ',
  history_en: 'Founded in 1942 in Nanupur, Fatikchhari, Chattogram, Nanupur Abu Sobhan High School has stood as a beacon of academic distinction, discipline, and moral enlightenment for over eight decades. Thousands of alumni have graduated to serve Bangladesh and global society with distinction across administration, medicine, engineering, education, and commerce.',
  history_bn: '১৯৪২ সালে চট্টগ্রামের ফটিকছড়ি উপজেলার নানুপুরে প্রতিষ্ঠিত নানুপুর আবু সোবহান উচ্চ বিদ্যালয় বিগত আট দশক ধরে শিক্ষা বিস্তার, মানবিক মূল্যবোধ ও জ্ঞানচর্চার এক অনন্য বাতিঘর। এখান থেকে শিক্ষা গ্রহণ করে হাজারো প্রাক্তন শিক্ষার্থী দেশ ও বিদেশের নানা ক্ষেত্রে কৃতিত্বের স্বাক্ষর রেখে চলেছেন।',
  vision_en: 'To nurture ethically grounded, scientifically curious, and globally competent leaders who illuminate community and nation.',
  vision_bn: 'নৈতিক মূল্যবোধসম্পন্ন, বিজ্ঞানমনস্ক ও বৈশ্বিক চ্যালেঞ্জ মোকাবেলায় সক্ষম আলোকিত নাগরিক গড়ে তোলা।',
  mission_en: 'Providing inclusive, high-quality secondary education equipped with modern pedagogical tools, moral values, sports, and community service.',
  mission_bn: 'আধুনিক শিক্ষা উপকরণ, নৈতিক মূল্যবোধ, বিজ্ঞানচর্চা এবং সহশিক্ষা কার্যক্রমের মাধ্যমে গুণগত মাধ্যমিক শিক্ষা নিশ্চিত করা।',
  headmaster_name_en: 'Mohammad Nurul Islam',
  headmaster_name_bn: 'মোহাম্মদ নুরুল ইসলাম',
  headmaster_message_en: 'It is a profound honor to welcome all alumni to the upcoming 85th Anniversary. Our school continues to uphold its rich tradition of academic excellence and integrity. We eagerly anticipate welcoming every batch home on 16 January 2027.',
  headmaster_message_bn: '৮৫ বছর পূর্তি উৎসব উপলক্ষে সকল প্রাক্তন শিক্ষার্থীকে উষ্ণ অভিনন্দন। আমাদের বিদ্যালয়ের ঐতিহ্য ও সুনাম রক্ষায় প্রাক্তন শিক্ষার্থীদের অবদান অনস্বীকার্য। ২০২৭ সালের ১৬ জানুয়ারি আপনাদের পদচারণায় মুখরিত হবে প্রিয় ক্যাম্পাস।',
  headmaster_photo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80',
  former_headmasters: [
    { name_en: 'Late Alhaj Abu Sobhan (Founder)', name_bn: 'মরহুম আলহাজ্ব আবু সোবহান (প্রতিষ্ঠাতা)', period: '1942 - 1955' },
    { name_en: 'Moulvi Abdul Gafur', name_bn: 'মৌলভি আব্দুল গফুর', period: '1955 - 1972' },
    { name_en: 'Master Nurul Absar', name_bn: 'মাস্টার নুরুল আবছার', period: '1973 - 1994' },
    { name_en: 'Md. Shamsul Alam', name_bn: 'মোঃ শামসুল আলম', period: '1995 - 2015' },
  ],
  sections: [
    { id: 'sec-1', key: 'hero_intro', title_en: 'School Overview & Identity', title_bn: 'বিদ্যালয় পরিচিতি ও সারসংক্ষেপ', is_enabled: true, order: 1 },
    { id: 'sec-2', key: 'headmaster_message', title_en: 'Headmaster Message', title_bn: 'প্রধান শিক্ষকের বাণী', is_enabled: true, order: 2 },
    { id: 'sec-3', key: 'history_timeline', title_en: 'Historical Timeline & Milestones', title_bn: 'ঐতিহাসিক পরিক্রমা ও মাইলফলক', is_enabled: true, order: 3 },
    { id: 'sec-4', key: 'ssc_results', title_en: 'SSC Academic Excellence & Results', title_bn: 'এসএসসি পরীক্ষার ফলাফল ও সাফল্য', is_enabled: true, order: 4 },
    { id: 'sec-5', key: 'headmaster_history', title_en: 'Distinguished Headmasters', title_bn: 'প্রধান শিক্ষকগণের তালিকা ও অবদান', is_enabled: true, order: 5 },
    { id: 'sec-6', key: 'facilities', title_en: 'Campus Infrastructure & Facilities', title_bn: 'ক্যাম্পাস অবকাঠামো ও সুবিধাসমূহ', is_enabled: true, order: 6 },
    { id: 'sec-7', key: 'contact_location', title_en: 'Location & Contact Information', title_bn: 'অবস্থান ও যোগাযোগের ঠিকানা', is_enabled: true, order: 7 },
  ],
  milestones: [
    { id: 'ms-1', year: '1942', title_en: 'Foundation of the Institution', title_bn: 'বিদ্যালয়ের শুভ প্রতিষ্ঠা', description_en: 'Established by local visionary Alhaj Abu Sobhan to bring secondary education to the greater Fatikchhari region.', description_bn: 'বৃহত্তর ফটিকছড়ি অঞ্চলে শিক্ষার আলো ছড়াতে দানবীর মরহুম আলহাজ্ব আবু সোবহান কর্তৃক বিদ্যালয়টি প্রতিষ্ঠিত হয়।', order: 1 },
    { id: 'ms-2', year: '1965', title_en: 'First Official SSC Examination Batch', title_bn: 'প্রথম এসএসসি পরীক্ষার্থী ব্যাচ', description_en: 'The first batch of students sat for secondary school certificate examinations under the Board of Intermediate and Secondary Education.', description_bn: 'মাধ্যমিক ও উচ্চ মাধ্যমিক শিক্ষা বোর্ডের অধীনে বিদ্যালয় থেকে প্রথম ব্যাচের শিক্ষার্থীরা এসএসসি পরীক্ষায় অংশগ্রহণ করে।', order: 2 },
    { id: 'ms-3', year: '1971', title_en: 'Heroic Role in Liberation War', title_bn: 'মহান মুক্তিযুদ্ধে গৌরবোজ্জ্বল ভূমিকা', description_en: 'Teachers and students actively took part in the 1971 Liberation War, turning the campus into an assembly center for freedom fighters.', description_bn: '১৯৭১ সালের মহান মুক্তিযুদ্ধে শিক্ষক ও শিক্ষার্থীদের সক্রিয় অংশগ্রহণ এবং মুক্তিকামী জনতার আশ্রয়স্থল হিসেবে কাজ করে বিদ্যালয়টি।', order: 3 },
    { id: 'ms-4', year: '2008', title_en: '65th Milestone Batch (Official Reference)', title_bn: '৬৫তম ব্যাচের মাইলফলক (অফিসিয়াল রেফারেন্স)', description_en: 'The landmark 65th Batch graduated, serving as the modern baseline year for institutional alumni numbering.', description_bn: 'ঐতিহাসিক ৬৫তম ব্যাচ শিক্ষা সমাপনী সম্পন্ন করে, যা পরবর্তীতে ব্যাচ গণনার প্রাতিষ্ঠানিক ভিত্তি হিসেবে স্বীকৃত হয়।', order: 4 },
    { id: 'ms-5', year: '2027', title_en: 'Historic 85th Anniversary Celebration', title_bn: 'ঐতিহাসিক ৮৫ বছর পূর্তি উৎসব', description_en: 'Grand celebration uniting 85 years of alumni, scholars, and community patrons on 16 January 2027.', description_bn: '১৬ জানুয়ারি ২০২৭ অনুষ্ঠিত হবে বিদ্যালয়ের গৌরবময় ৮৫ বছর পূর্তি মহোৎসব ও প্রাক্তন শিক্ষার্থী পুনর্মিলনী।', order: 5 },
  ],
  headmaster_history: [
    { id: 'hm-1', name_en: 'Late Alhaj Abu Sobhan (Founder)', name_bn: 'মরহুম আলহাজ্ব আবু সোবহান (প্রতিষ্ঠাতা)', designation_en: 'Founder & Honorary Principal', designation_bn: 'প্রতিষ্ঠাতা ও অনারারি প্রধান', tenure_en: '1942 – 1955', tenure_bn: '১৯৪২ – ১৯৫৫', biography_en: 'Eminent philanthropist and social reformer who donated ancestral land and funds to establish the school.', biography_bn: 'বিদ্যালয় প্রতিষ্ঠার স্বপ্নদ্রষ্টা ও দানবীর, যিনি নিজের জমি ও অর্থ ব্যয়ে বিদ্যালয়টি গড়ে তোলেন।', is_current: false, order: 1 },
    { id: 'hm-2', name_en: 'Moulvi Abdul Gafur', name_bn: 'মৌলভি আব্দুল গফুর', designation_en: 'Headmaster', designation_bn: 'প্রধান শিক্ষক', tenure_en: '1955 – 1972', tenure_bn: '১৯৫৫ – ১৯৭২', biography_en: 'Pioneered formal curriculum expansion, established the core academic staff, and nurtured the school through testing eras.', biography_bn: 'আধুনিক পাঠ্যক্রম প্রবর্তন ও বিদ্যালয়ের প্রাথমিক প্রাতিষ্ঠানিক ভিত্তি সুদৃঢ় করেন।', is_current: false, order: 2 },
    { id: 'hm-3', name_en: 'Master Nurul Absar', name_bn: 'মাস্টার নুরুল আবছার', designation_en: 'Headmaster', designation_bn: 'প্রধান শিক্ষক', tenure_en: '1973 – 1994', tenure_bn: '১৯৭৩ – ১৯৯৪', biography_en: 'Renowned pedagogue whose strict discipline and educational dedication shaped thousands of scholars over two decades.', biography_bn: 'দুই দশকেরও বেশি সময় ধরে কঠোর শৃঙ্খলা ও মেধার বিকাশে হাজারো কৃতি শিক্ষার্থী গড়ে তোলেন।', is_current: false, order: 3 },
    { id: 'hm-4', name_en: 'Md. Shamsul Alam', name_bn: 'মোঃ শামসুল আলম', designation_en: 'Headmaster', designation_bn: 'প্রধান শিক্ষক', tenure_en: '1995 – 2015', tenure_bn: '১৯৯৫ – ২০১৫', biography_en: 'Spearheaded modern scientific laboratory upgrades, computer lab introduction, and historic SSC success rates.', biography_bn: 'আধুনিক বিজ্ঞান গবেষণাগার, কম্পিউটার ল্যাব স্থাপন এবং এসএসসি পাসের হারের উল্লেখযোগ্য উন্নয়ন ঘটান।', is_current: false, order: 4 },
    { id: 'hm-5', name_en: 'Mohammad Nurul Islam', name_bn: 'মোহাম্মদ নুরুল ইসলাম', designation_en: 'Headmaster (Current)', designation_bn: 'প্রধান শিক্ষক (বর্তমান)', tenure_en: '2016 – Present', tenure_bn: '২০১৬ – বর্তমান', biography_en: 'Directing digital education integration, campus renovations, and co-hosting the 85th anniversary celebration.', biography_bn: 'ডিজিটাল ক্লাস ও অবকাঠামোগত সংস্কার পরিচালনা করছেন এবং ৮৫ বছর পূর্তি উৎসবের সহ-পৃষ্ঠপোষক হিসেবে নেতৃত্ব দিচ্ছেন।', is_current: true, order: 5 },
  ],
  ssc_results: [
    { id: 'ssc-2025', academic_year: 2025, exam_year: 2025, candidates: 245, passed: 241, failed: 4, pass_rate: 98.37, gpa5_count: 54, highest_gpa: 5.00, notable_achievements_en: 'Outstanding performance across Science and Commerce streams.', notable_achievements_bn: 'বিজ্ঞান ও ব্যবসায় শিক্ষা শাখায় অভূতপূর্ব ফলাফল।', status: 'published' },
    { id: 'ssc-2024', academic_year: 2024, exam_year: 2024, candidates: 238, passed: 232, failed: 6, pass_rate: 97.48, gpa5_count: 48, highest_gpa: 5.00, notable_achievements_en: 'Top ranked in Fatikchhari Upazila for combined GPA average.', notable_achievements_bn: 'ফটিকছড়ি উপজেলায় সম্মিলিত জিপিএ ফলাফলে শীর্ষস্থান অর্জন।', status: 'published' },
    { id: 'ssc-2023', academic_year: 2023, exam_year: 2023, candidates: 220, passed: 214, failed: 6, pass_rate: 97.27, gpa5_count: 42, highest_gpa: 5.00, notable_achievements_en: '100% pass rate achieved in Science stream.', notable_achievements_bn: 'বিজ্ঞান শাখায় শতভাগ পাসের গৌরব অর্জন।', status: 'published' },
    { id: 'ssc-2022', academic_year: 2022, exam_year: 2022, candidates: 215, passed: 208, failed: 7, pass_rate: 96.74, gpa5_count: 39, highest_gpa: 5.00, notable_achievements_en: 'Exemplary performance with board merit positions.', notable_achievements_bn: 'চট্টগ্রাম শিক্ষা বোর্ডে বিশেষ মেধা তালিকায় অন্তর্ভুক্তি।', status: 'published' },
    { id: 'ssc-2021', academic_year: 2021, exam_year: 2021, candidates: 198, passed: 192, failed: 6, pass_rate: 96.97, gpa5_count: 35, highest_gpa: 5.00, notable_achievements_en: 'Successfully navigated pandemic challenges with hybrid learning.', notable_achievements_bn: 'করোনাকালীন প্রতিকূলতার মাঝেও চমকপ্রদ সাফল্য।', status: 'published' },
  ],
  facility_items: [
    { id: 'fac-1', title_en: 'Modern Science Laboratories', title_bn: 'আধুনিক বিজ্ঞান গবেষণাগার', description_en: 'Fully equipped physics, chemistry, and biology labs with modern instruments and hands-on experiment stations.', description_bn: 'পদার্থ, রসায়ন ও জীববিজ্ঞানের আধুনিক যন্ত্রপাতি সমৃদ্ধ বাস্তবমুখী গবেষণাগার।', icon: 'Atom', order: 1 },
    { id: 'fac-2', title_en: 'Sheikh Russel Digital Computer Lab', title_bn: 'শেখ রাসেল ডিজিটাল কম্পিউটার ল্যাব', description_en: 'High-speed broadband workstations for ICT training, programming, and digital literacy development.', description_bn: 'উচ্চগতির ইন্টারনেট সুবিধাসহ কম্পিউটার প্রশিক্ষণ ও তথ্যপ্রযুক্তি শিক্ষার সুব্যবস্থা।', icon: 'Laptop', order: 2 },
    { id: 'fac-3', title_en: 'Historic Library & Study Hall', title_bn: 'সমৃদ্ধ গ্রন্থাগার ও পাঠাগার', description_en: 'Over 8,000 books spanning Bengali literature, history, science, reference encyclopedias, and periodicals.', description_bn: 'আট হাজারেরও বেশি বই, সাহিত্য সাময়িকী, বিশ্বকোষ ও গবেষণাপত্র সমৃদ্ধ পাঠাগার।', icon: 'BookOpen', order: 3 },
    { id: 'fac-4', title_en: 'Spacious Athletic Playground', title_bn: 'বিশাল খেলার মাঠ ও ক্রীড়া কমপ্লেক্স', description_en: 'Expansive field hosting football tournaments, cricket matches, athletic meets, and annual reunions.', description_bn: 'ফুটবল, ক্রিকেট ও বার্ষিক ক্রীড়া প্রতিযোগিতার জন্য উন্মুক্ত বিস্তৃত মাঠ।', icon: 'Trophy', order: 4 },
  ],
  address_en: 'Nanupur, Fatikchhari, Chattogram 4350, Bangladesh',
  address_bn: 'নানুপুর, ফটিকছড়ি, চট্টগ্রাম ৪৩৫০, বাংলাদেশ',
  phone: '+880 1819-000000',
  email: 'info@nanupuralumni.org',
  facilities: ['Modern Science Laboratories', 'Digital Computer Lab', 'Historic Library & Archive', 'Full-Sized Athletic Playground', 'Multi-Purpose Auditorium', 'Mosque Complex'],
  images: [
    'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=80',
    'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80'
  ]
};

export const initialAssociationInfo: AssociationInfo = {
  name_en: 'Nanupur Abu Sobhan High School Alumni Association',
  name_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ',
  established_year: 1985,
  intro_en: 'The Alumni Association brings together alumni across all generations to foster lifelong fellowship, support the continued development of our alma mater, and organize milestone celebrations.',
  intro_bn: 'প্রাক্তন শিক্ষার্থী পরিষদ বিদ্যালয়ের সকল ব্যাচের প্রাক্তন শিক্ষার্থীদের পারস্পরিক সৌহার্দ্য ও মেলবন্ধনের কেন্দ্রীয় প্ল্যাটফর্ম। বিদ্যালয়ের সার্বিক উন্নয়ন ও পুনর্মিলনী আয়োজনে পরিষদ নিরলস কাজ করে যাচ্ছে।',
  mission_en: 'Unite all batches, build welfare initiatives for needy students, preserve the institutional legacy, and host inspiring reunions.',
  mission_bn: 'সকল ব্যাচের শিক্ষার্থীদের ঐক্যবদ্ধ করা, শিক্ষার্থীদের বৃত্তি প্রদান ও মেধা সহায়তা এবং বর্ণাঢ্য পুনর্মিলনী উদযাপনের মাধ্যমে ভ্রাতৃত্বের বন্ধন সুদৃঢ় করা।',
  vision_en: 'A vibrant global network of alumni supporting educational transformation and societal welfare.',
  vision_bn: 'একটি শক্তিশালী ও আন্তর্জাতিক প্রাক্তন শিক্ষার্থী নেটওয়ার্ক গঠন যা বিদ্যালয় ও সমাজের কল্যাণে অগ্রণী ভূমিকা রাখবে।',
  objectives_en: [
    'Organize milestone reunions including the 85th Anniversary on 16 Jan 2027',
    'Establish academic scholarships for meritorious school students',
    'Modernize school science and computer lab facilities',
    'Maintain a comprehensive database of all school alumni'
  ],
  objectives_bn: [
    '১৬ জানুয়ারি ২০২৭ তারিখে বিদ্যালয়ের ঐতিহাসিক ৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনী উদযাপন',
    'মেধাবী শিক্ষার্থীদের জন্য শিক্ষাবৃত্তি ও শিক্ষা উপকরণ সহায়তা প্রদান',
    'বিদ্যালয়ের বিজ্ঞানাগার ও কম্পিউটার ল্যাব আধুনিকীকরণ',
    'সকল ব্যাচের প্রাক্তন শিক্ষার্থীদের সমন্বিত ডাটাবেজ সংরক্ষণ'
  ],
  contact_phone: '+880 1819-123456',
  contact_email: 'reunion2027@nanupuralumni.org',
  address_en: 'Nanupur Abu Sobhan High School Campus, Fatikchhari, Chattogram, Bangladesh',
  address_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাঙ্গণ, ফটিকছড়ি, চট্টগ্রাম, বাংলাদেশ'
};

export const initialCommittee: CommitteeMember[] = [
  {
    id: 'comm-1',
    name_en: 'Engr. Mohammad Rafiqul Islam',
    name_bn: 'প্রকৌশলী মোহাম্মদ রফিকুল ইসলাম',
    designation_en: 'President, Alumni Association',
    designation_bn: 'সভাপতি, প্রাক্তন শিক্ষার্থী পরিষদ',
    batch_year: 1985,
    tenure: '2025 - 2027',
    order_index: 1,
    is_active: true,
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'comm-2',
    name_en: 'Advocate Shamsuddin Ahmed',
    name_bn: 'অ্যাডভোকেট শামসুদ্দিন আহমেদ',
    designation_en: 'Convener, 85th Anniversary Committee',
    designation_bn: 'আহ্বায়ক, ৮৫ বছর পূর্তি উদযাপন কমিটি',
    batch_year: 1982,
    tenure: '2025 - 2027',
    order_index: 2,
    is_active: true,
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'comm-3',
    name_en: 'Dr. Md. Tariqul Hasan',
    name_bn: 'ড. মোঃ তারিকুল হাসান',
    designation_en: 'General Secretary',
    designation_bn: 'সাধারণ সম্পাদক',
    batch_year: 1995,
    tenure: '2025 - 2027',
    order_index: 3,
    is_active: true,
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'comm-4',
    name_en: 'Kazi Farhan Tanvir',
    name_bn: 'কাজী ফারহান তানভীর',
    designation_en: 'Member Secretary, Registration & IT Sub-committee',
    designation_bn: 'সদস্য সচিব, নিবন্ধন ও আইটি উপকমিটি',
    batch_year: 2005,
    tenure: '2025 - 2027',
    order_index: 4,
    is_active: true,
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'comm-5',
    name_en: 'Nasreen Akhtar Chowdhury',
    name_bn: 'নাসরিন আক্তার চৌধুরী',
    designation_en: 'Finance Secretary',
    designation_bn: 'অর্থ সম্পাদক',
    batch_year: 2002,
    tenure: '2025 - 2027',
    order_index: 5,
    is_active: true,
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80'
  }
];

export const initialNotices: Notice[] = [
  {
    id: 'not-1',
    title_en: 'Official Announcement: 85th Anniversary Reunion Date Finalized on 16 January 2027',
    title_bn: 'বিজ্ঞপ্তি: আগামী ১৬ জানুয়ারি ২০২৭ তারিখে ৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনীর তারিখ চূড়ান্ত',
    content_en: 'The Executive Committee of Nanupur Abu Sobhan High School Alumni Association is pleased to inform all alumni that the 85th Anniversary Celebration will take place on Saturday, 16 January 2027 on the school grounds. Online registration is now formally open.',
    content_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদের কার্যনির্বাহী কমিটির সিদ্ধান্ত মোতাবেক সকল প্রাক্তন শিক্ষার্থীকে জানানো যাচ্ছে যে, আগামী ১৬ জানুয়ারি ২০২৭, শনিবার বিদ্যালয় প্রাঙ্গণে ৮৫ বছর পূর্তি উৎসব অনুষ্ঠিত হবে। অনলাইন নিবন্ধন আনুষ্ঠানিকভাবে উন্মুক্ত করা হয়েছে।',
    publish_date: '2026-03-01',
    is_featured: true,
    is_active: true,
    category: 'Announcement',
    attachment_name: '85th_Anniversary_Notice_NASH.pdf'
  },
  {
    id: 'not-2',
    title_en: 'Batch Representative Meeting & Coordination Schedule',
    title_bn: 'ব্যাচ প্রতিনিধিদের মতবিনিময় সভা ও সমন্বয় বিজ্ঞপ্তি',
    content_en: 'All batch representatives from SSC 1960 to 2026 are invited to attend the coordination session at the school auditorium or via virtual conference.',
    content_bn: 'এসএসসি ১৯৬০ থেকে ২০২৬ সালের সকল ব্যাচের প্রতিনিধিদের পুনর্মিলনী প্রস্তুতি সংক্রান্ত সভায় অংশ নেওয়ার জন্য বিশেষভাবে অনুরোধ করা হচ্ছে।',
    publish_date: '2026-02-15',
    is_featured: false,
    is_active: true,
    category: 'Coordination'
  }
];

export const initialNews: NewsPost[] = [
  {
    id: 'news-1',
    slug: 'anniversary-registration-launched-online',
    title_en: 'Alumni Association Launches Digital Portal for 85th Anniversary Registration',
    title_bn: '৮৫ বছর পূর্তি উৎসবের ডিজিটাল নিবন্ধন পোর্টাল চালু করল প্রাক্তন শিক্ষার্থী পরিষদ',
    content_en: 'The Alumni Association of Nanupur Abu Sobhan High School has officially introduced the online registration portal with automated batch verification, instant mobile banking payments (bKash, Nagad), and unique QR-code entry passes.',
    content_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদ স্বয়ংক্রিয় ব্যাচ নির্ধারণ, মোবাইল ব্যাংকিং (বিকাশ, নগদ) পেমেন্ট এবং কিউআর কোড সম্বলিত প্রবেশপত্র সহ পূর্ণাঙ্গ ডিজিটাল নিবন্ধন পোর্টাল চালু করেছে।',
    category: 'Event Updates',
    author: 'IT & Media Wing',
    publish_date: '2026-03-05',
    is_published: true,
    views: 1240,
    featured_image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'news-2',
    slug: 'school-grounds-renovation-underway',
    title_en: 'Historic School Pavilion and Sports Grounds Prepared for Grand Celebration',
    title_bn: '৮৫ বছর পূর্তি উপলক্ষে ঐতিহাসিক স্কুল মাঠ ও প্রাঙ্গণ সজ্জিতকরণ',
    content_en: 'Preparations are actively underway on the campus to welcome over 4,000 alumni and guests for a memorable day of nostalgia, cultural performances, and networking.',
    content_bn: 'ঐতিহাসিক দিনটিকে স্মরণীয় করে রাখতে ক্যাম্পাস প্রাঙ্গণ সংস্কার এবং ৪,০০০ এর অধিক প্রাক্তন শিক্ষার্থী ও অতিথিদের বরণ করতে জোর প্রস্তুতি চলছে।',
    category: 'Campus News',
    author: 'Press Committee',
    publish_date: '2026-02-28',
    is_published: true,
    views: 890,
    featured_image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80'
  }
];

export const initialRegistrations: Registration[] = [];

export const initialTokens: EntryToken[] = [];

export const initialDesignations: CommitteeDesignation[] = [
  { id: 'desig-1', title_en: 'Convenor', title_bn: 'আহ্বায়ক', default_order: 1 },
  { id: 'desig-2', title_en: 'Joint Convenor', title_bn: 'যুগ্ম আহ্বায়ক', default_order: 2 },
  { id: 'desig-3', title_en: 'Member Secretary', title_bn: 'সদস্য সচিব', default_order: 3 },
  { id: 'desig-4', title_en: 'Joint Member Secretary', title_bn: 'যুগ্ম সদস্য সচিব', default_order: 4 },
  { id: 'desig-5', title_en: 'Finance Secretary / Treasurer', title_bn: 'অর্থ সম্পাদক / কোষাধ্যক্ষ', default_order: 5 },
  { id: 'desig-6', title_en: 'Publicity & Media Secretary', title_bn: 'প্রচার ও মিডিয়া সম্পাদক', default_order: 6 },
  { id: 'desig-7', title_en: 'Batch Coordination Secretary', title_bn: 'ব্যাচ সমন্বয় সম্পাদক', default_order: 7 },
  { id: 'desig-8', title_en: 'Reception Secretary', title_bn: 'অভ্যর্থনা সম্পাদক', default_order: 8 },
  { id: 'desig-9', title_en: 'Cultural & Event Secretary', title_bn: 'সাংস্কৃতিক ও অনুষ্ঠান সম্পাদক', default_order: 9 },
  { id: 'desig-10', title_en: 'Executive Member', title_bn: 'কার্যনির্বাহী সদস্য', default_order: 10 },
  { id: 'desig-11', title_en: 'Chief Advisor', title_bn: 'প্রধান উপদেষ্টা', default_order: 11 },
  { id: 'desig-12', title_en: 'Advisor', title_bn: 'উপদেষ্টা', default_order: 12 },
];

export const initialCommittees: Committee[] = [
  {
    id: 'comm-85-convening',
    name_en: '85th Anniversary Celebration Convening Committee',
    name_bn: '৮৫ বছর পূর্তি উৎসব উদযাপন আহ্বায়ক কমিটি',
    committee_type: 'convening',
    tenure_start: '2026-01-01',
    tenure_end: '2027-02-28',
    tenure_label: '2026–2027',
    description_en: 'Official organizing committee entrusted with coordinating all facets of the historic 85th Anniversary Celebration & Grand Alumni Reunion on 16 January 2027.',
    description_bn: '১৬ জানুয়ারি ২০২৭ অনুষ্ঠিতব্য ঐতিহাসিক ৮৫ বছর পূর্তি উৎসব ও পুনর্মিলনীর সার্বিক প্রস্তুতি ও বাস্তবায়নে গঠিত আহ্বায়ক কমিটি।',
    is_current: true,
    is_active: true,
    order_index: 1,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'comm-exec-2024-2026',
    name_en: 'Executive Committee (2024–2026)',
    name_bn: 'কার্যনির্বাহী পরিষদ (২০২৪–২০২৬)',
    committee_type: 'executive',
    tenure_start: '2024-01-01',
    tenure_end: '2026-12-31',
    tenure_label: '2024–2026',
    description_en: 'Elected leadership managing the permanent affairs of the Nanupur Abu Sobhan High School Alumni Association.',
    description_bn: 'নানুপুর আবু সোবহান উচ্চ বিদ্যালয় প্রাক্তন শিক্ষার্থী পরিষদের স্থায়ী পরিচালনা পরিষদ।',
    is_current: false,
    is_active: true,
    order_index: 2,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'comm-advisory',
    name_en: 'Advisory Council',
    name_bn: 'উপদেষ্টা পরিষদ',
    committee_type: 'advisory',
    tenure_start: '2024-01-01',
    tenure_end: '2028-12-31',
    tenure_label: 'Permanent Advisory',
    description_en: 'Distinguished senior alumni, veteran educators, and community leaders providing strategic guidance and patronship.',
    description_bn: 'বিদ্যালয়ের প্রবীণ কৃতি শিক্ষার্থী, শিক্ষাবিদ ও সমাজহিতৈষীদের সমন্বয়ে গঠিত পরামর্শক পরিষদ।',
    is_current: false,
    is_active: true,
    order_index: 3,
    created_at: '2024-01-01T00:00:00Z',
  },
];

export const initialCommitteeMembers: CommitteeMemberItem[] = [
  {
    id: 'cm-1',
    committee_id: 'comm-85-convening',
    user_id: 'user-super-admin',
    custom_name_en: 'Engr. Safayet Hossain',
    custom_name_bn: 'প্রকৌশলী সাফায়েত হোসেন',
    designation_en: 'Convenor',
    designation_bn: 'আহ্বায়ক',
    batch_year: 1992,
    batch_name: '49th Batch (1992)',
    phone: '01815-858391',
    email: 'safayet@nanupuralumni.org',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'cm-2',
    committee_id: 'comm-85-convening',
    custom_name_en: 'Advocate Didarul Alam',
    custom_name_bn: 'অ্যাডভোকেট দিদারুল আলম',
    designation_en: 'Member Secretary',
    designation_bn: 'সদস্য সচিব',
    batch_year: 1995,
    batch_name: '52nd Batch (1995)',
    phone: '01817-734794',
    email: 'didar@nanupuralumni.org',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'cm-3',
    committee_id: 'comm-85-convening',
    custom_name_en: 'Dr. Mohammad Nazmul Huda',
    custom_name_bn: 'ডাঃ মোহাম্মদ নাজমুল হুদা',
    designation_en: 'Joint Convenor',
    designation_bn: 'যুগ্ম আহ্বায়ক',
    batch_year: 1993,
    batch_name: '50th Batch (1993)',
    phone: '01816-033880',
    email: 'nazmul@nanupuralumni.org',
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'cm-4',
    committee_id: 'comm-85-convening',
    custom_name_en: 'Kazi Farhan Tanvir',
    custom_name_bn: 'কাজী ফারহান তানভীর',
    designation_en: 'Finance Secretary',
    designation_bn: 'অর্থ সম্পাদক',
    batch_year: 2005,
    batch_name: '62nd Batch (2005)',
    phone: '01955-550880',
    email: 'farhan@nanupuralumni.org',
    photo_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'cm-5',
    committee_id: 'comm-85-convening',
    custom_name_en: 'Abdur Rahim Chowdhury',
    custom_name_bn: 'আব্দুর রহিম চৌধুরী',
    designation_en: 'Batch Coordination Secretary',
    designation_bn: 'ব্যাচ সমন্বয় সম্পাদক',
    batch_year: 2008,
    batch_name: '65th Batch (2008)',
    phone: '01819-000005',
    email: 'rahim@nanupuralumni.org',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    order_index: 5,
    is_active: true,
  },
];

export const initialOfflineCenters: OfflineRegistrationCenter[] = [
  {
    id: 'off-1',
    name_en: 'Ramkrishna Oushadhalaya',
    name_bn: 'রামকৃষ্ণ ঔষধালয়',
    address_en: 'Nabidur Rahman Market, Nanupur Bazar, Fatikchhari, Chattogram',
    address_bn: 'নবীদুর রহমান মার্কেট, নানুপুর বাজার, ফটিকছড়ি, চট্টগ্রাম',
    phone: '01815-858391',
    contact_person: 'Subhash Chandra Das',
    timings: 'Daily 9:00 AM – 8:00 PM',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'off-2',
    name_en: 'Didar & Brothers',
    name_bn: 'দিদার এন্ড ব্রাদার্স',
    address_en: 'UP Road, Nanupur Bazar, Fatikchhari, Chattogram',
    address_bn: 'ইউনিয়ন পরিষদ রোড, নানুপুর বাজার, ফটিকছড়ি, চট্টগ্রাম',
    phone: '01817-734794',
    contact_person: 'Didarul Alam',
    timings: 'Daily 9:00 AM – 9:00 PM',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'off-3',
    name_en: 'Al Matwaf Travels & Tours',
    name_bn: 'আল মাতওয়াফ ট্রাভেলস এন্ড ট্যুরস',
    address_en: '83 T&S Tower (3rd Floor), Muradpur, Chattogram',
    address_bn: '৮৩ টি এন্ড এস টাওয়ার (৪র্থ তলা/৩য় ফ্লোর), মুরাদপুর, চট্টগ্রাম',
    phone: '01816-033880',
    contact_person: 'Engr. Safayet',
    timings: 'Saturday to Thursday: 10:00 AM – 7:00 PM',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'off-4',
    name_en: 'District Shilpakala Academy',
    name_bn: 'জেলা শিল্পকলা একাডেমি',
    address_en: 'M M Ali Road, Dampara, Chattogram',
    address_bn: 'এম এম আলী রোড, দামপাড়া, চট্টগ্রাম',
    phone: '01955-550880',
    contact_person: 'Cultural Desk',
    timings: 'Daily 10:00 AM – 6:00 PM',
    order_index: 4,
    is_active: true,
  },
];

export const initialGates = [
  {
    id: 'gate-1',
    gate_name: 'Gate 01 - Main Gate (VIP & Guests)',
    gate_code: 'GATE-01',
    description: 'Main entrance for VIPs, Teachers, and Special Guests',
    display_order: 1,
    is_active: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'gate-2',
    gate_name: 'Gate 02 - Alumni Batches 1942–1990',
    gate_code: 'GATE-02',
    description: 'Dedicated entry for senior alumni',
    display_order: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'gate-3',
    gate_name: 'Gate 03 - Alumni Batches 1991–2010',
    gate_code: 'GATE-03',
    description: 'Mid-generation alumni entry point',
    display_order: 3,
    is_active: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'gate-4',
    gate_name: 'Gate 04 - Alumni Batches 2011–Present',
    gate_code: 'GATE-04',
    description: 'Recent batches & young alumni entry point',
    display_order: 4,
    is_active: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const initialHeroConfig: HeroConfig = {
  badge_en: '1942–2027 • 85 Glorious Years of Legacy',
  badge_bn: '১৯৪২–২০২৭ • ৮৫ বছরের গৌরবময় ঐতিহ্য',
  show_badge: true,

  headline_en: '85th Anniversary Celebration &',
  headline_bn: '৮৫ বছর পূর্তি উৎসব ও',
  headline_highlight_en: 'Grand Alumni Reunion 2027',
  headline_highlight_bn: 'প্রাক্তন শিক্ষার্থী পুনর্মিলনী ২০২৭',

  subheading_en: 'Welcoming all beloved alumni of Nanupur Abu Sobhan High School to an unforgettable reunion of camaraderie, nostalgia, and community.',
  subheading_bn: 'ঐতিহ্যবাহী নানুপুর আবু সোবহান উচ্চ বিদ্যালয়ের সকল প্রাক্তন শিক্ষার্থীকে প্রাণঢালা আমন্ত্রণ। আসুন শৈশব ও কৈশোরের সোনালী স্মৃতিতে অবগাহন করি।',

  date_text_en: '16 January 2027 (Saturday)',
  date_text_bn: '১৬ জানুয়ারি ২০২৭ (শনিবার)',
  show_date: true,

  venue_text_en: 'Nanupur Abu Sobhan High School Campus',
  venue_text_bn: 'বিদ্যালয় প্রাঙ্গণ, নানুপুর, ফটিকছড়ি, চট্টগ্রাম',
  show_venue: true,

  fee_text_en: 'Registration Fee: ৳1,000 BDT',
  fee_text_bn: 'নিবন্ধন ফি: ১,০০০ টাকা',
  show_fee: true,

  primary_cta_text_en: 'Register for Reunion Now',
  primary_cta_text_bn: 'অনলাইনে নিবন্ধন করুন',
  primary_cta_link: 'register',
  show_primary_cta: true,

  secondary_cta_text_en: 'Verify Token Code',
  secondary_cta_text_bn: 'পাস যাচাই করুন',
  secondary_cta_link: 'verify',
  show_secondary_cta: true,

  countdown_target_date: '2027-01-16T08:00:00+06:00',
  countdown_label_en: 'Countdown to Historic Reunion',
  countdown_label_bn: 'উৎসব শুরু হতে বাকি',
  show_countdown: true,

  background_style: 'gradient',
  background_image_url: '',
  hero_image_url: '',
  overlay_opacity: 20,
  accent_color: '#fbbf24',
};

